<?php declare(strict_types=1);


namespace Awyiss\Queue\Task\Design;


use Queue\Queue\Task;
use ZipArchive;


/**
 * WebfontDownloadTask
 * Download webfonts from the external API, unzip them and generate the SCSS file
 */
class WebfontDownloadTask extends Task {
	/**
	 * @inheritDoc
	 */
	public ?int $retries = 3;
	/**
	 * @inheritDoc
	 */
	public ?int $timeout = 60;


	/**
	 * @inheritDoc
	 * @param array $data
	 * @param int $jobId
	 * @return void
	 */
	public function run(array $data, int $jobId): void {
		$fonts = $data['fonts'] ?? [];

		if (!$fonts) {
			return;
		}

		foreach ($fonts as $key => $font) {
			// Local path for the font
			$fontPath = ROOT . DS . CUSTOM_DIR . DS . 'assets' . DS . 'font' . DS . $font['id'];

			// Convert the font variants to the correct format
			foreach ($font['variants'] as $variantKey => $variant) {
				if ($variant === '400i') {
					$font['variants'][ $variantKey ] = 'italic';
				}
				elseif ((int)$variant === 400) {
					$font['variants'][ $variantKey ] = 'regular';
				}
				elseif (str_ends_with($variant, 'i')) {
					$font['variants'][ $variantKey ] .= 'talic';
				}

				// Update the font variants in the outer array
				$fonts[ $key ]['variants'][ $variantKey ] = $font['variants'][ $variantKey ];
			}

			// External API URL
			$downloadUrl = $this->getDownloadUrl($font);

			// Local path for the downloaded zip
			$downloadPath = $fontPath . '.zip';

			// Create the font directory if it doesn't exist
			if (!is_dir($fontPath)) {
				mkdir($fontPath, 0755, true);
			}

			// Download the Zip
			$fileData = file_get_contents($downloadUrl);
			file_put_contents($downloadPath, $fileData);

			// Unzip the file
			$zip = new ZipArchive();
			$zip->open($downloadPath);
			$zip->extractTo($fontPath);
			$zip->close();

			// Remove the zip file
			unlink($downloadPath);
		}

		$content = $this->generateScssFile($fonts);
		if ($content) {
			file_put_contents(ROOT . DS . CUSTOM_DIR . DS . 'assets' . DS . 'scss' . DS . 'webfonts.scss', $content);
		}
	}


	/**
	 * Generate the SCSS file for the webfonts
	 *
	 * @param array $fonts
	 * @return string
	 */
	protected function generateScssFile(array $fonts): string {
		$fileContents = <<<EOT
/**
 * Webfont SCSS file
 * This file is generated by the WebfontDownloadTask after
 * modifying the design settings in the backend.
 *
 * Do not edit this file directly.
 * Changes will be overwritten.
 */


EOT;

		foreach ($fonts as $font) {
			// Local path for the font
			$fontPath = ROOT . DS . CUSTOM_DIR . DS . 'assets' . DS . 'font' . DS . $font['id'];

			// If no variants are specified, use all known variants
			$font['variants'] = $font['variants'] ?: [
				'100',
				'100italic',
				'200',
				'200italic',
				'300',
				'300italic',
				'regular',
				'italic',
				'500',
				'500italic',
				'600',
				'600italic',
				'700',
				'700italic',
				'800',
				'800italic',
				'900',
				'900italic',
			];

			foreach ($font['variants'] as $variant) {
				$variant = (string)$variant;
				$fontWeight = in_array($variant, ['regular', 'italic'], true) ? 400 : (int)$variant;
				$fontStyle = str_ends_with($variant, 'italic') ? 'italic' : 'normal';
				$fileName = $font['id'] . '-' . $font['version'] . '-latin_latin-ext-' . $variant . '.woff2';

				if (!file_exists($fontPath . DS . $fileName)) {
					$fileName = $font['id'] . '-' . $font['version'] . '-latin-' . $variant . '.woff2';
				}

				// If the file still does not exist, skip this variant
				if (!file_exists($fontPath . DS . $fileName)) {
					continue;
				}

				$fileContents .= $this->buildFontFaceBlock($font['id'], $font['name'], $fontStyle, $fontWeight, $fileName);
			}
		}

		return $fileContents;
	}


	/**
	 * @param string $fontId
	 * @param string $fontName
	 * @param string $fontStyle
	 * @param int $fontWeight
	 * @param string $fileName
	 * @return string
	 */
	protected function buildFontFaceBlock(string $fontId, string $fontName, string $fontStyle, int $fontWeight, string $fileName): string {
		return <<<EOT
@font-face {
    font-display:swap;
    font-family:'$fontName';
    font-style:$fontStyle;
    font-weight:$fontWeight;
    src:url('../font/$fontId/$fileName') format('woff2');
}


EOT;
	}


	/**
	 * @param array $font
	 * @return string
	 */
	protected function getDownloadUrl(array $font): string {
		// Build the query data
		$queryData = [
			'download' => 'zip',
			'subsets' => 'latin,latin-ext',
			'formats' => 'woff2',
		];

		if (!empty($font['variants'])) {
			$queryData['variants'] = implode(',', array_unique($font['variants']));
		}

		return 'https://gwfh.mranftl.com/api/fonts/' . $font['id'] . '?' . http_build_query($queryData);
	}
}
