<?php declare(strict_types=1);


use Migrations\BaseSeed;


/**
 * Attributes seed.
 */
class AttributesCustomSeed extends BaseSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$data = [
			[
				'id' => 1,
				'scope' => 'News',
				'identifier' => 'date',
				'title' => 'Datum',
				'type' => 'date',
				'hasIndex' => 0,
				'fieldset' => 'conditions',
				'inputType' => 'date',
				'defaultValue' => null,
				'required' => 1,
				'translatable' => 0,
				'columnSpan' => '12/12',
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 2,
				'scope' => 'News',
				'identifier' => 'teaser',
				'title' => 'Teaser',
				'type' => 'text',
				'hasIndex' => 0,
				'fieldset' => 'content',
				'inputType' => 'texteditor',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '12/12',
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 3,
				'scope' => 'News',
				'identifier' => 'text',
				'title' => 'Text',
				'type' => 'text',
				'hasIndex' => 0,
				'fieldset' => 'content',
				'inputType' => 'texteditor',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '12/12',
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 4,
				'scope' => 'Contents',
				'identifier' => 'backgroundColor',
				'title' => 'Hintergrundfarbe',
				'type' => 'varchar(50)',
				'hasIndex' => 0,
				'fieldset' => null,
				'inputType' => 'select',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '12/12',
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 5,
				'scope' => 'Contents',
				'identifier' => 'teaser',
				'title' => 'Teaser',
				'type' => 'text',
				'hasIndex' => 0,
				'fieldset' => null,
				'inputType' => 'texteditor',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '12/12',
				'systemOrder' => 2,
				'active' => 0,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 6,
				'scope' => 'Cars',
				'identifier' => 'freeText',
				'title' => 'Freitext',
				'type' => 'longtext',
				'hasIndex' => 0,
				'fieldset' => 'content',
				'inputType' => 'textarea',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '6/12',
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 7,
				'scope' => 'Cars',
				'identifier' => 'dropdownSelect',
				'title' => 'Auswahlfeld (Pflichtfeld, übersetzbar)',
				'type' => 'varchar(50)',
				'hasIndex' => 0,
				'fieldset' => 'content',
				'inputType' => 'selectMultiple',
				'defaultValue' => null,
				'required' => 1,
				'translatable' => 1,
				'columnSpan' => '6/12',
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 8,
				'scope' => 'GlobalContents',
				'identifier' => 'freeText',
				'title' => 'Freitext',
				'type' => 'longtext',
				'hasIndex' => 0,
				'fieldset' => 'content',
				'inputType' => 'textarea',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '6/12',
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 9,
				'scope' => 'GlobalContents',
				'identifier' => 'freeTextInactive',
				'title' => 'Freitext',
				'type' => 'longtext',
				'hasIndex' => 0,
				'fieldset' => 'content',
				'inputType' => 'textarea',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '6/12',
				'systemOrder' => 2,
				'active' => 0,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 10,
				'scope' => 'GlobalContents',
				'identifier' => 'teaser',
				'title' => 'Teaser',
				'type' => 'longtext',
				'hasIndex' => 0,
				'fieldset' => 'content',
				'inputType' => 'textarea',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '6/12',
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 11,
				'scope' => 'Cars',
				'identifier' => 'inputList',
				'title' => 'Input List',
				'type' => 'json',
				'hasIndex' => 0,
				'fieldset' => 'presentation',
				'inputType' => 'inputList',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '6/12',
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 12,
				'scope' => 'Cars',
				'identifier' => 'inputKeyValueList',
				'title' => 'Input Key-Value List',
				'type' => 'json',
				'hasIndex' => 0,
				'fieldset' => 'presentation',
				'inputType' => 'inputKeyValueList',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '6/12',
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 13,
				'scope' => 'Cars',
				'identifier' => 'dummyPw',
				'title' => 'Password',
				'type' => 'password',
				'hasIndex' => 0,
				'fieldset' => 'content',
				'inputType' => 'password',
				'defaultValue' => null,
				'required' => 0,
				'translatable' => 0,
				'columnSpan' => '9/12',
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
		];

		$table = $this->table('attributes');
		$table->truncate();
		$table->insert($data)->save();
	}
}
