<?php declare(strict_types=1);


use Migrations\AbstractSeed;


/**
 * Attributes seed.
 */
class AttributesCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$la_data = [
			[
				'id' => 1,
				'scope' => 'news',
				'identifier' => 'date',
				'title' => 'Datum',
				'type' => 'date',
				'has_index' => 0,
				'fieldset' => 'conditions',
				'input_type' => 'date',
				'default_value' => null,
				'required' => 1,
				'translatable' => 0,
				'column_span' => '12/12',
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 2,
				'scope' => 'news',
				'identifier' => 'teaser',
				'title' => 'Teaser',
				'type' => 'text',
				'has_index' => 0,
				'fieldset' => 'content',
				'input_type' => 'texteditor',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '12/12',
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 3,
				'scope' => 'news',
				'identifier' => 'text',
				'title' => 'Text',
				'type' => 'text',
				'has_index' => 0,
				'fieldset' => 'content',
				'input_type' => 'texteditor',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '12/12',
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 4,
				'scope' => 'contents',
				'identifier' => 'background_color',
				'title' => 'Hintergrundfarbe',
				'type' => 'varchar(50)',
				'has_index' => 0,
				'fieldset' => '',
				'input_type' => 'select',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '12/12',
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 5,
				'scope' => 'contents',
				'identifier' => 'teaser',
				'title' => 'Teaser',
				'type' => 'text',
				'has_index' => 0,
				'fieldset' => '',
				'input_type' => 'texteditor',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '12/12',
				'system_order' => 2,
				'active' => 0,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 6,
				'scope' => 'cars',
				'identifier' => 'free_text',
				'title' => 'Freitext',
				'type' => 'longtext',
				'has_index' => 0,
				'fieldset' => 'content',
				'input_type' => 'textarea',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '6/12',
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 7,
				'scope' => 'cars',
				'identifier' => 'dropdown_select',
				'title' => 'Auswahlfeld (Pflichtfeld, übersetzbar)',
				'type' => 'varchar(50)',
				'has_index' => 0,
				'fieldset' => 'content',
				'input_type' => 'select_multiple',
				'default_value' => null,
				'required' => 1,
				'translatable' => 1,
				'column_span' => '6/12',
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 8,
				'scope' => 'widgets',
				'identifier' => 'free_text',
				'title' => 'Freitext',
				'type' => 'longtext',
				'has_index' => 0,
				'fieldset' => 'content',
				'input_type' => 'textarea',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '6/12',
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 9,
				'scope' => 'widgets',
				'identifier' => 'free_text_inactive',
				'title' => 'Freitext',
				'type' => 'longtext',
				'has_index' => 0,
				'fieldset' => 'content',
				'input_type' => 'textarea',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '6/12',
				'system_order' => 2,
				'active' => 0,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 10,
				'scope' => 'widgets',
				'identifier' => 'teaser',
				'title' => 'Teaser',
				'type' => 'longtext',
				'has_index' => 0,
				'fieldset' => 'content',
				'input_type' => 'textarea',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '6/12',
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 11,
				'scope' => 'cars',
				'identifier' => 'input_list',
				'title' => 'Input List',
				'type' => 'json',
				'has_index' => 0,
				'fieldset' => 'presentation',
				'input_type' => 'input_list',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '6/12',
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 12,
				'scope' => 'cars',
				'identifier' => 'input_key_value_list',
				'title' => 'Input Key-Value List',
				'type' => 'json',
				'has_index' => 0,
				'fieldset' => 'presentation',
				'input_type' => 'input_key_value_list',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '6/12',
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 13,
				'scope' => 'cars',
				'identifier' => 'dummy_pw',
				'title' => 'Password',
				'type' => 'password',
				'has_index' => 0,
				'fieldset' => 'content',
				'input_type' => 'password',
				'default_value' => null,
				'required' => 0,
				'translatable' => 0,
				'column_span' => '9/12',
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
		];

		$lo_table = $this->table('attributes');
		$lo_table->truncate();
		$lo_table->insert($la_data)->save();
	}
}
