<?php declare(strict_types=1);


use Migrations\BaseSeed;


/**
 * Configuration seed.
 */
class ConfigurationCustomSeed extends BaseSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$data = [
			[
				'id' => 4,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'systemOrder.direction',
				'value' => '3',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 5,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'categories.associationName',
				'value' => 'Newscategories',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 6,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'categories.enabled',
				'value' => '1',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 8,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'categories.allowUnassigned',
				'value' => '1',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 13,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'contents.enabled',
				'value' => '1',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 14,
				'realm' => 'Backend',
				'scope' => 'Newscategories',
				'identifier' => 'categories.associationName',
				'value' => 'Pages',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 16,
				'realm' => 'Backend',
				'scope' => 'Newscategories',
				'identifier' => 'categories.allowAggregation',
				'value' => '1',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 18,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'categories.includeParentCategories',
				'value' => '1',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 20,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'categories.allowAggregation',
				'value' => '1',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 46,
				'realm' => 'Frontend',
				'scope' => 'Media',
				'identifier' => 'defaultBreakpoints',
				'value' => '[2560,1920,1680,1440,1280,1024,768,640,480,320]',
				'languageShortcode' => null,
				'description' => 'Testbeschreibung oder so',
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 54,
				'realm' => 'Backend',
				'scope' => 'Cars',
				'identifier' => 'translatable',
				'value' => '1',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 55,
				'realm' => 'Backend',
				'scope' => 'Employers',
				'identifier' => 'systemOrder.field',
				'value' => 'systemOrder',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 57,
				'realm' => 'Backend',
				'scope' => 'Employers',
				'identifier' => 'translatable',
				'value' => '1',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 58,
				'realm' => 'Backend',
				'scope' => 'Employers',
				'identifier' => 'splitIntoLanguages',
				'value' => '0',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 59,
				'realm' => 'Backend',
				'scope' => 'Newscategories',
				'identifier' => 'categories.enabled',
				'value' => '1',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 61,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'overview.displayedFields',
				'value' => '["parentId","attributes.date"]',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 63,
				'realm' => 'Backend',
				'scope' => 'ContentTemplates',
				'identifier' => 'overview.displayedFields',
				'value' => '["fileName","createdBy","createdOn"]',
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 66,
				'realm' => 'Backend',
				'scope' => 'Newscategories',
				'identifier' => 'systemOrder.field',
				'value' => 'title',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 67,
				'realm' => 'Backend',
				'scope' => 'System',
				'identifier' => 'interface.editor',
				'value' => 'tinymce',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 68,
				'realm' => 'Frontend',
				'scope' => 'System',
				'identifier' => 'meta.titleAppendix',
				'value' => 'AquaTrek Logistics',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 69,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'systemOrder.field',
				'value' => 'attributes.date',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 71,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'mediaFolders.autoCreate',
				'value' => '1',
				'languageShortcode' => null,
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 72,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'somethingTranslatable',
				'value' => 'english',
				'languageShortcode' => 'en',
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 73,
				'realm' => 'Backend',
				'scope' => 'News',
				'identifier' => 'somethingTranslatable',
				'value' => 'deutsch',
				'languageShortcode' => 'de',
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 74,
				'realm' => 'Frontend',
				'scope' => 'News',
				'identifier' => 'somethingTranslatableForFrontend',
				'value' => 'english',
				'languageShortcode' => 'en',
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 75,
				'realm' => 'Frontend',
				'scope' => 'News',
				'identifier' => 'somethingTranslatableForFrontend',
				'value' => 'deutsch',
				'languageShortcode' => 'de',
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 77,
				'realm' => 'Frontend',
				'scope' => 'System',
				'identifier' => 'dummyConfig',
				'value' => 'dummy zu',
				'languageShortcode' => 'zu',
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 78,
				'realm' => 'Backend',
				'scope' => 'System',
				'identifier' => 'dummyConfig',
				'value' => 'dummy en',
				'languageShortcode' => 'en',
				'description' => null,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
		];

		$table = $this->table('configuration');
		$table->insert($data)->save();
	}
}
