<?php declare(strict_types=1);


use Migrations\AbstractSeed;


/**
 * Configuration seed.
 */
class ConfigurationCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$data = [
			[
				'id' => 4,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'system_order.direction',
				'value' => '3',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 5,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'categories.association_name',
				'value' => 'Newscategories',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 6,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'categories.enabled',
				'value' => '1',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 8,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'categories.allow_unassigned',
				'value' => '1',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 13,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'contents.enabled',
				'value' => '1',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 14,
				'realm' => 'Backend',
				'scope' => 'newscategories',
				'identifier' => 'categories.association_name',
				'value' => 'Pages',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 16,
				'realm' => 'Backend',
				'scope' => 'newscategories',
				'identifier' => 'categories.allow_aggregation',
				'value' => '1',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 18,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'categories.include_parent_categories',
				'value' => '1',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 20,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'categories.allow_aggregation',
				'value' => '1',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 46,
				'realm' => 'Frontend',
				'scope' => 'media',
				'identifier' => 'default_breakpoints',
				'value' => '[2560,1920,1680,1440,1280,1024,768,640,480,320]',
				'language_shortcode' => null,
				'description' => 'Testbeschreibung oder so',
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 54,
				'realm' => 'Backend',
				'scope' => 'cars',
				'identifier' => 'translatable',
				'value' => '1',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 55,
				'realm' => 'Backend',
				'scope' => 'employers',
				'identifier' => 'system_order.field',
				'value' => 'system_order',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 57,
				'realm' => 'Backend',
				'scope' => 'employers',
				'identifier' => 'translatable',
				'value' => '1',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 58,
				'realm' => 'Backend',
				'scope' => 'employers',
				'identifier' => 'split_into_languages',
				'value' => '0',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 59,
				'realm' => 'Backend',
				'scope' => 'newscategories',
				'identifier' => 'categories.enabled',
				'value' => '1',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 61,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'overview.displayed_fields',
				'value' => '["parent_id","attributes.date"]',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 63,
				'realm' => 'Backend',
				'scope' => 'content_templates',
				'identifier' => 'overview.displayed_fields',
				'value' => '["file_name","created_by","created_on"]',
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 66,
				'realm' => 'Backend',
				'scope' => 'newscategories',
				'identifier' => 'system_order.field',
				'value' => 'title',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 67,
				'realm' => 'Backend',
				'scope' => 'system',
				'identifier' => 'interface.editor',
				'value' => 'tinymce',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 68,
				'realm' => 'Frontend',
				'scope' => 'system',
				'identifier' => 'meta.title_appendix',
				'value' => 'AquaTrek Logistics',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 69,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'system_order.field',
				'value' => 'attributes.date',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 71,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'media_folders.auto_create',
				'value' => '1',
				'language_shortcode' => null,
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 72,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'something_translatable',
				'value' => 'english',
				'language_shortcode' => 'en',
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 73,
				'realm' => 'Backend',
				'scope' => 'news',
				'identifier' => 'something_translatable',
				'value' => 'deutsch',
				'language_shortcode' => 'de',
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 74,
				'realm' => 'Frontend',
				'scope' => 'news',
				'identifier' => 'something_translatable_for_frontend',
				'value' => 'english',
				'language_shortcode' => 'en',
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 75,
				'realm' => 'Frontend',
				'scope' => 'news',
				'identifier' => 'something_translatable_for_frontend',
				'value' => 'deutsch',
				'language_shortcode' => 'de',
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 77,
				'realm' => 'Frontend',
				'scope' => 'system',
				'identifier' => 'dummy_config',
				'value' => 'dummy zu',
				'language_shortcode' => 'zu',
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 78,
				'realm' => 'Backend',
				'scope' => 'system',
				'identifier' => 'dummy_config',
				'value' => 'dummy en',
				'language_shortcode' => 'en',
				'description' => null,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
		];

		$table = $this->table('configuration');
		$table->insert($data)->save();
	}
}
