<?php declare(strict_types=1);


use Migrations\AbstractSeed;


/**
 * Contents seed.
 */
class ContentsCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$la_data = [
			[
				'id' => 1,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 8,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 2,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<module class="mceNonEditable" data-identifier="test" data-label="Testmodul">{"key":"value"}</module>',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 9,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 1,
				'title' => 'H1-Überschrift',
				'title_tag' => 'h1',
				'subtitle' => 'Aber Farbe ändern kann ich nicht. Nur Hintergrund',
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 12,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 10,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 13,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 11,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<table> <thead> <tr> <th scope="col">&nbsp;</th> <th style="text-align: right;" scope="col">Preisgruppe 1</th> <th style="text-align: right;" scope="col">Preisgruppe 2</th> </tr> </thead> <tbody> <tr> <td>Montag - Freitag</td> <td style="text-align: right;">99,-</td> <td style="text-align: right;">82,-</td> </tr> <tr> <td>Samstag &amp; Sonntag</td> <td style="text-align: right;">123,-</td> <td style="text-align: right;">118,.</td> </tr> </tbody> </table>
<p style="text-align: center;"><a class="Button" href="https://cms.de/">Jetzt buchen</a></p>
',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 15,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 14,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 16,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 3,
				'title' => 'Aktuelle Meldungen',
				'title_tag' => 'h2',
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<module class="mceNonEditable" data-identifier="newsListing" data-label="News-Listing">{"paginate":false,"items":3,"offset":null}</module>
',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 0,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 17,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 4,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 18,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 5,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<h2>Zwischen&uuml;berschrift (h2) mit<br><span class="Textcolor-Contrast">integriertem Zeilenumbruch.</span><br><span class="Textcolor-Contrast">In Farbe.</span></h2>
',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 21,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 6,
				'title' => 'Block #1',
				'title_tag' => 'h3',
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, animi commodi cum dolor enim et expedita impedit libero magni, modi nulla, quae quia quibusdam quis rem suscipit tempora vero voluptatem?</p>
<p>Aliquam consectetur delectus maiores voluptates. Ad aliquid commodi ea, est impedit incidunt ipsam iusto laudantium maxime modi mollitia nostrum odio officia optio pariatur perspiciatis quo, sint tenetur ullam unde voluptatibus?</p>
',
				'link' => null,
				'column_width' => '1/3',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 24,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 7,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<h2 class="FontAlternative">Spezielle Headline (h2),</h2>
<h2>direkt gefolgt von weiterer h2 (Nogo!)</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, animi commodi cum dolor enim et expedita impedit libero magni, modi nulla, quae quia quibusdam quis rem suscipit tempora vero voluptatem?</p>
<p>Aliquam consectetur delectus maiores voluptates. Ad aliquid commodi ea, est impedit incidunt ipsam iusto laudantium maxime modi mollitia nostrum odio officia optio pariatur perspiciatis quo, sint tenetur ullam unde voluptatibus?</p>
',
				'link' => null,
				'column_width' => '3/5',
				'column_indent' => '1/5',
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 25,
				'page_id' => 7,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 26,
				'page_id' => 7,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 25,
				'title' => 'Aktuelle Meldungen',
				'title_tag' => 'h1',
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<module class="mceNonEditable" data-identifier="newsListing" data-label="News-Listing">{"titleTag":"h2","paginate":true,"itemsPerPage":3}</module>
',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 27,
				'page_id' => 32,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 28,
				'page_id' => 32,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 27,
				'title' => 'Dit war nüscht, wa?',
				'title_tag' => 'h1',
				'subtitle' => 'Seite nicht gefunden',
				'subtitle_tag' => 'h2',
				'text' => '<p>Tut mir leid, gell, aber die Seite wurde nicht gefunden.</p>
',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => 1,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 31,
				'page_id' => 29,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 30,
				'title' => 'Heuer bei uns an!',
				'title_tag' => 'h1',
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => 32,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 32,
				'page_id' => 25,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 33,
				'title' => 'Titel H1',
				'title_tag' => 'h1',
				'subtitle' => 'Untertitel auch H1',
				'subtitle_tag' => 'h1',
				'text' => '<p>Dies ist ein neuer Inhalt. Hier k&ouml;nnte eine &Uuml;bersicht mit neuen Stellen kommen.</p>
',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 33,
				'page_id' => 25,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 35,
				'page_id' => 3,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 36,
				'page_id' => 3,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 35,
				'title' => 'Historie',
				'title_tag' => 'h1',
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 38,
				'page_id' => 3,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 37,
				'title' => 'Bildergalerie',
				'title_tag' => 'h2',
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 0,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 39,
				'page_id' => 3,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 38,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 2,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 0,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 10,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 1,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<h2><a href="de/maenner/fussball/body" target="_blank" rel="noopener">Testuntertitel<sub>3</sub> mit Verlinkung</a></h2>
<ol>
<li><strong>Lorem&sup2; ipsum&sup3; dolor sit amet,</strong> consectetur adipisicing elit. Consequatur in quia repellat sequi tempora? Accusantium amet architecto consequuntur dicta fuga impedit in nesciunt, perspiciatis porro provident reiciendis, similique tenetur voluptatum. Beatae culpa ex molestiae nobis nulla quidem rem, voluptas. Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis! <strong><span class="Uppercase">Aperiam, atque consectetur eaque eos praesentium quam vero.</span></strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur in quia repellat sequi tempora? Accusantium amet architecto consequuntur dicta fuga impedit in nesciunt, perspiciatis porro provident reiciendis, similique tenetur voluptatum beatae cul.</li>
<li><strong>Lorem ipsum dolor sit amet,</strong> consectetur adipisicing elit. Consequatur in quia repellat sequi tempora? Accusantium amet architecto consequuntur dicta fuga impedit in nesciunt, perspiciatis porro provident reiciendis, similique tenetur voluptatum. Beatae culpa ex molestiae nobis nulla quidem rem, voluptas. Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis! Aperiam, atque consectetur eaque eos praesentium quam vero.</li>
<li><strong>Lorem ipsum dolor sit amet,</strong> consectetur adipisicing elit. Consequatur in quia repellat sequi tempora? Accusantium amet architecto consequuntur dicta fuga impedit in nesciunt, perspiciatis porro provident reiciendis, similique tenetur voluptatum.</li>
</ol>
',
				'link' => null,
				'column_width' => '1/2',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 20,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 5,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/3',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 22,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 6,
				'title' => 'Block #2',
				'title_tag' => 'h3',
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, animi commodi cum dolor enim et expedita impedit libero magni, modi nulla, quae quia quibusdam quis rem suscipit tempora vero voluptatem?</strong></p>
<p>Aliquam consectetur delectus maiores voluptates. Ad aliquid commodi ea, est impedit incidunt ipsam iusto laudantium maxime modi mollitia nostrum odio officia optio pariatur perspiciatis quo, sint tenetur ullam unde voluptatibus?</p>
',
				'link' => null,
				'column_width' => '1/3',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => 1,
				'changed_on' => (new \Cake\I18n\DateTime('now'))->addHours(10)->format('Y-m-d H:i:s'),
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 30,
				'page_id' => 29,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 34,
				'page_id' => 25,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 32,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p>BLABLABLAAAAAAAAAAAAAAA</p>
',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 37,
				'page_id' => 3,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 40,
				'page_id' => 3,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 38,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 3,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 11,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 1,
				'title' => 'Beatae culpa ex molestiae nobis nulla quidem rem, voluptas',
				'title_tag' => 'h3',
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p><strong>Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis!</strong> Aperiam, atque consectetur eaque eos praesentium quam vero. Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis! Aperiam, atque consectetur eaque eos praesentium quam vero.<br>Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis! Aperiam, atque consectetur eaque eos praesentium quam vero.</p>
<hr>
<p>Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. <a href="https://www.youtube.com/watch?v=BoFUI1Xv4Dw" target="_blank" rel="noopener">Commodi maiores, nobis!</a> Aperiam, atque consectetur eaque eos praesentium quam vero. Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis! Aperiam, atque consectetur eaque eos praesentium quam vero.</p>
',
				'link' => 'https://www.youtube.com/watch?v=BoFUI1Xv4Dw',
				'column_width' => '1/2',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 19,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 5,
				'title' => 'Testtitel',
				'title_tag' => 'h3',
				'subtitle' => 'Testsubtitel',
				'subtitle_tag' => 'h4',
				'text' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur in quia repellat sequi tempora? Accusantium amet architecto consequuntur dicta fuga impedit in nesciunt, perspiciatis porro provident reiciendis, similique tenetur voluptatum.</p>
<p>Beatae culpa ex molestiae nobis nulla quidem rem, voluptas. Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis! Aperiam, atque consectetur eaque eos praesentium quam vero.</p>
',
				'link' => null,
				'column_width' => '2/3',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 23,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 6,
				'title' => 'Block #3',
				'title_tag' => 'h3',
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, animi commodi cum dolor enim et expedita impedit libero magni, modi nulla, quae quia quibusdam quis rem suscipit tempora vero voluptatem?</p>
<p>Aliquam consectetur delectus maiores voluptates. Ad aliquid commodi ea, est impedit incidunt ipsam iusto laudantium maxime modi mollitia nostrum odio officia optio pariatur perspiciatis quo, sint tenetur ullam unde voluptatibus?</p>
',
				'link' => null,
				'column_width' => '1/3',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 41,
				'page_id' => 3,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 38,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 4,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 14,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 1,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, animi commodi cum dolor enim et expedita impedit libero magni, modi nulla, quae quia quibusdam quis rem suscipit tempora vero voluptatem?</p>
<blockquote> <p>Aliquam consectetur delectus maiores voluptates. Ad aliquid commodi ea, est impedit incidunt ipsam iusto laudantium maxime modi mollitia nostrum odio officia optio pariatur perspiciatis quo, sint tenetur ullam unde voluptatibus?</p> </blockquote>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, animi commodi cum dolor enim et expedita impedit libero magni, modi nulla, quae quia quibusdam quis rem suscipit tempora vero voluptatem?</p>
<ul>
<li>Lorem ipsum dolor sit amet</li>
<li>consectetur adipisicing elit</li>
<li>Aliquid, animi commodi cum dolor enim et expedita impedit libero magni</li>
<li>modi nulla, quae quia quibusdam quis rem suscipit tempora vero voluptatem?</li>
</ul>
',
				'link' => null,
				'column_width' => '3/5',
				'column_indent' => '1/5',
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 42,
				'page_id' => 3,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 38,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 5,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 5,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 6,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 6,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 7,
				'page_id' => 1,
				'content_area_id' => 1,
				'content_template_id' => 2,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 7,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 43,
				'page_id' => 20,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<h2>Zwischen&uuml;berschrift (h2) mit<br><span class="Textcolor-Contrast">integriertem Zeilenumbruch.</span><br><span class="Textcolor-Contrast">In Farbe.</span></h2>',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 44,
				'page_id' => 20,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p><awyiss-responsive-image>{"mediaId":"2"}</awyiss-responsive-image></p>',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 45,
				'page_id' => 20,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p>Content with inline img tag</p><p><awyiss-responsive-image>{"mediaId":"4"}</awyiss-responsive-image></p><p>between two paragraphs</p>',
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 46,
				'page_id' => 20,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'survey_id' => 1,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 48,
				'page_id' => 20,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 45,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p>Nested content</p>',
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 47,
				'page_id' => 20,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 48,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p>Nested content</p>',
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 50,
				'page_id' => 50,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => '{"a":"a","b":"b"}',
				'form_id' => null,
				'survey_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => '1',
				'changed_on' => '2025-08-16 10:29:50',
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 52,
				'page_id' => 50,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 50,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<h1>Atjkjque doloribus enim harum incidunt laudantium quos repellat&hellip;</h1>
',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'survey_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 53,
				'page_id' => 50,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 50,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<h2><a href="de/maenner/fussball/body" target="_blank" rel="noopener">Testuntertitel<sub>3</sub> mit Verlinkung</a></h2>
<ol>
<li><strong><a href="#Content102" rel="lightbox">Lorem&sup2; ipsum&sup3; dolor sit amet</a>,</strong> consectetur adipisicing elit. Consequatur in quia repellat sequi tempora? Accusantium amet architecto consequuntur dicta fuga impedit in nesciunt, perspiciatis porro provident reiciendis, similique tenetur voluptatum. Beatae culpa ex molestiae nobis nulla quidem rem, voluptas. Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. <a href="de/maenner/fussball/mannschaften/profis/news/neues-cms-auf-cakephp-basis-revolutioniert-webentwicklung" rel="lightbox">Commodi maiores, nobis!</a> <strong><span class="Uppercase">Aperiam, atque consectetur eaque eos praesentium quam vero.</span></strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur in quia repellat sequi tempora? Accusantium amet architecto consequuntur dicta fuga impedit in nesciunt, perspiciatis porro provident reiciendis, similique tenetur voluptatum beatae cul.</li>
<li><strong><a href="media/global-3/gladiator.mp4" rel="lightbox">Lorem ipsum dolor sit amet</a>,</strong> consectetur adipisicing elit. Consequatur in quia repellat sequi tempora? <a href="de/aktuelles/#Content93" rel="lightbox">Accusantium amet architecto consequuntur dicta fuga impedit</a> in nesciunt, perspiciatis porro provident reiciendis, similique tenetur voluptatum. Beatae culpa ex molestiae nobis nulla quidem rem, voluptas. Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis! Aperiam, atque consectetur eaque eos praesentium quam vero.</li>
<li><strong>&#9989; Lorem ipsum dolor sit amet,</strong> consectetur adipisicing elit. Consequatur in quia repellat sequi tempora? Accusantium amet architecto consequuntur dicta fuga impedit in nesciunt, perspiciatis porro provident reiciendis, similique tenetur voluptatum.</li>
</ol>
',
				'link' => null,
				'column_width' => '1/2',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => '{"ak":"av","ck":"cv"}',
				'form_id' => null,
				'survey_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 54,
				'page_id' => 50,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 53,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'survey_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 55,
				'page_id' => 50,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 50,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<h3><a id="Anker1"></a>Beatae culpa ex molestiae nobis nulla quidem rem, voluptas</h3>
<p><strong>Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis!</strong> Aperiam, atque consectetur eaque eos praesentium quam vero. Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis! Aperiam, atque consectetur eaque eos praesentium quam vero.<br>Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis! Aperiam, atque consectetur eaque eos praesentium quam vero.</p>
<hr>
<p>Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. <a href="https://www.youtube.com/watch?v=BoFUI1Xv4Dw" target="_blank" rel="noopener">Commodi maiores, nobis!</a> Aperiam, atque consectetur eaque eos praesentium quam vero. Atque doloribus enim harum incidunt laudantium quos repellat sapiente veniam. Commodi maiores, nobis! Aperiam, atque consectetur eaque eos praesentium quam vero.</p>',
				'link' => null,
				'column_width' => '1/2',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => '{"ak":"av","bk":"bv","ck":"cv"}',
				'form_id' => null,
				'survey_id' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 56,
				'page_id' => 50,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 55,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<table>
<thead>
<tr>
<th scope="col">&nbsp;</th>
<th style="text-align: right;" scope="col">Preisgruppe 1</th>
<th style="text-align: right;" scope="col">Preisgruppe 2</th>
</tr>
</thead>
<tbody>
<tr>
<td>Montag - Freitag</td>
<td style="text-align: right;">99,-</td>
<td style="text-align: right;">82,-</td>
</tr>
<tr>
<td>Samstag &amp; Sonntag</td>
<td style="text-align: right;">123,-</td>
<td style="text-align: right;">118,.</td>
</tr>
</tbody>
</table>
<p style="text-align: center;"><a class="Button" href="https://cms.de">Jetzt buchen</a></p>',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => '{"ak":"av","bk":"bv","ck":"cv"}',
				'form_id' => null,
				'survey_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 51,
				'page_id' => 50,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 50,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, animi commodi cum dolor enim et expedita impedit libero magni, modi nulla, quae quia quibusdam quis rem suscipit tempora vero voluptatem?</p>
<blockquote>
<p>Aliquam consectetur delectus maiores voluptates. Ad aliquid commodi ea, est impedit incidunt ipsam iusto laudantium maxime modi mollitia nostrum odio officia optio pariatur perspiciatis quo, sint tenetur ullam unde voluptatibus?</p>
</blockquote>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, animi commodi cum dolor enim et expedita impedit libero magni, modi nulla, quae quia quibusdam quis rem suscipit tempora vero voluptatem?</p>
<ul>
<li>Lorem ipsum dolor sit amet</li>
<li>consectetur adipisicing elit</li>
<li>Aliquid, animi commodi cum dolor enim et expedita impedit libero magni</li>
<li>modi nulla, quae quia quibusdam quis rem suscipit tempora vero voluptatem?</li>
</ul>',
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => '1/5',
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'survey_id' => null,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 57,
				'page_id' => 50,
				'content_area_id' => 1,
				'content_template_id' => 1,
				'parent_id' => 51,
				'title' => null,
				'title_tag' => null,
				'subtitle' => null,
				'subtitle_tag' => null,
				'text' => null,
				'link' => 'https://www.youtube.com/watch?v=BoFUI1Xv4Dw',
				'column_width' => '1/2',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'css' => 'background-color:red;',
				'duplicate_of' => null,
				'data' => null,
				'form_id' => null,
				'survey_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
		];

		$lo_table = $this->table('contents');
		$lo_table->insert($la_data)->save();
	}
}
