<?php declare(strict_types=1);


use Migrations\BaseSeed;


/**
 * Forms seed.
 */
class FormsCustomSeed extends BaseSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$data = [
			[
				'id' => 1,
				'title' => 'Kontaktformular',
				'identifier' => 'contact',
				'sendEmail' => 0,
				'emailTemplateId' => 1,
				'sendConfirmationEmail' => 0,
				'confirmationEmailTemplateId' => 3,
				'ownerEmail' => 'awyiss@cms.de',
				'ownerName' => 'Awyiss CMS',
				'userEmail' => '$email',
				'userName' => '$vorname $nachname',
				'cc' => '[]',
				'bcc' => '[]',
				'subject' => 'Betreff für E-Mail{{ von $vorname $nachname}}',
				'subjectConfirmation' => 'Betreff für Bestätigung',
				'salutation' => null,
				'salutationConfirmation' => 'Hallo $vorname $nachname',
				'successMessage' => '<h1 style="text-align: center;">Vielen Dank für Ihre Anfrage{{,<br>$firstname $lastname|}}.</h1>
<p style="text-align: center;">Wir werden uns zeitnah mit Ihnen, {{$vorname $nachname|lieber Kunde oder Kunde-to-be}}, in Verbindung setzen. Versprochen.</p>
<p>Info text with inline img tag<br><awyiss-responsive-image>{"mediaId":"4"}</awyiss-responsive-image></p>',
				'multistep' => 0,
				'transportProfile' => 'debug',
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 2,
				'title' => 'Kontaktformular2',
				'identifier' => 'contact2',
				'sendEmail' => 1,
				'emailTemplateId' => 1,
				'sendConfirmationEmail' => 1,
				'confirmationEmailTemplateId' => 3,
				'ownerEmail' => 'awyiss@cms.de',
				'ownerName' => 'Awyiss CMS',
				'userEmail' => '$email',
				'userName' => '$vorname $nachname',
				'cc' => '[]',
				'bcc' => '[]',
				'subject' => 'Betreff für E-Mail{{ von $vorname $nachname}}',
				'subjectConfirmation' => 'Betreff für Bestätigung',
				'salutation' => null,
				'salutationConfirmation' => 'Hallo $vorname $nachname',
				'successMessage' => '<h1 style="text-align: center;">Vielen Dank für Ihre Anfrage{{,<br>$firstname $lastname|}}.</h1>
<p style="text-align: center;">Wir werden uns zeitnah mit Ihnen, {{$vorname $nachname|lieber Kunde oder Kunde-to-be}}, in Verbindung setzen. Versprochen.</p>',
				'multistep' => 0,
				'transportProfile' => 'debug',
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 3,
				'title' => 'Kontaktformular3',
				'identifier' => 'contact3',
				'sendEmail' => 1,
				'emailTemplateId' => 1,
				'sendConfirmationEmail' => 1,
				'confirmationEmailTemplateId' => 3,
				'ownerEmail' => 'awyiss@cms.de',
				'ownerName' => null,
				'userEmail' => '$email',
				'userName' => '$vorname $nachname',
				'cc' => '[]',
				'bcc' => '[]',
				'subject' => null,
				'subjectConfirmation' => 'Betreff für Bestätigung',
				'salutation' => null,
				'salutationConfirmation' => 'Hallo $vorname $nachname',
				'successMessage' => '<h1 style="text-align: center;">Vielen Dank für Ihre Anfrage{{,<br>$firstname $lastname|}}.</h1>
<p style="text-align: center;">Wir werden uns zeitnah mit Ihnen, {{$vorname $nachname|lieber Kunde oder Kunde-to-be}}, in Verbindung setzen. Versprochen.</p>',
				'multistep' => 0,
				'transportProfile' => 'debug',
				'active' => 0,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 4,
				'title' => 'Kontaktformular4',
				'identifier' => 'contact4',
				'sendEmail' => 1,
				'emailTemplateId' => 1,
				'sendConfirmationEmail' => 1,
				'confirmationEmailTemplateId' => 3,
				'ownerEmail' => 'awyiss@cms.de',
				'ownerName' => null,
				'userEmail' => '$email',
				'userName' => '$vorname $nachname',
				'cc' => '[]',
				'bcc' => '[]',
				'subject' => null,
				'subjectConfirmation' => 'Betreff für Bestätigung',
				'salutation' => null,
				'salutationConfirmation' => 'Hallo $vorname $nachname',
				'successMessage' => '<h1 style="text-align: center;">Vielen Dank für Ihre Anfrage{{,<br>$firstname $lastname|}}.</h1>
<p style="text-align: center;">Wir werden uns zeitnah mit Ihnen, {{$vorname $nachname|lieber Kunde oder Kunde-to-be}}, in Verbindung setzen. Versprochen.</p>',
				'multistep' => 0,
				'transportProfile' => 'debug',
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 5,
				'title' => 'Kontaktformular5',
				'identifier' => 'contact5',
				'sendEmail' => 1,
				'emailTemplateId' => 1,
				'sendConfirmationEmail' => 1,
				'confirmationEmailTemplateId' => 3,
				'ownerEmail' => 'awyiss@cms.de',
				'ownerName' => null,
				'userEmail' => '$email',
				'userName' => '$vorname $nachname',
				'cc' => '[]',
				'bcc' => '[]',
				'subject' => null,
				'subjectConfirmation' => 'Betreff für Bestätigung',
				'salutation' => null,
				'salutationConfirmation' => 'Hallo $vorname $nachname',
				'successMessage' => '<h1 style="text-align: center;">Vielen Dank für Ihre Anfrage{{,<br>$firstname $lastname|}}.</h1>
<p style="text-align: center;">Wir werden uns zeitnah mit Ihnen, {{$vorname $nachname|lieber Kunde oder Kunde-to-be}}, in Verbindung setzen. Versprochen.</p>',
				'multistep' => 0,
				'transportProfile' => 'debug',
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
		];

		$table = $this->table('forms');
		$table->insert($data)->save();
	}
}
