<?php declare(strict_types=1);

use Migrations\AbstractSeed;


/**
 * FormElements seed.
 */
class FormElementsCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$data = [
			[
				'id' => 1,
				'formId' => 1,
				'parentId' => null,
				'type' => 'fieldset',
				'identifier' => 'persoenlicheDaten',
				'title' => 'Persönliche Daten',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 4,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'select',
				'identifier' => 'anrede',
				'title' => 'Anrede',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => '[{"key":null,"value":null,"_translations":{"de":{"key":"","value":""},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"","value":"Frau"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"","value":"Herr"},"es":{"key":"","value":"Senor"}}},{"key":null,"value":null,"_translations":{"de":{"key":"","value":"Divers"},"es":{"key":"","value":"Diversos"}}}]',
				'columnWidth' => '1/2',
				'columnIndent' => null,
				'columnLast' => 1,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 2,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'text',
				'identifier' => 'vorname',
				'title' => 'Vorname',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => null,
				'columnWidth' => '1/2',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 1,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 7,
				'formId' => 1,
				'parentId' => null,
				'type' => 'textarea',
				'identifier' => 'nachricht',
				'title' => 'Nachricht',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => '<p>Test</p>',
				'options' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 1,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 3,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'text',
				'identifier' => 'nachname',
				'title' => 'Nachname',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => null,
				'columnWidth' => '1/2',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => 'BackgroundColor-Light',
				'required' => 1,
				'systemOrder' => 3,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 9,
				'formId' => 1,
				'parentId' => null,
				'type' => 'checkbox',
				'identifier' => 'datenschutzAkzeptiert',
				'title' => 'Datenschutz akzeptiert',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => '[{"key":null,"value":null,"_translations":{"de":{"key":"Ja","value":"Ich habe die Datenschutzerkl\\u00e4rung gelesen und akzeptiert"},"es":{"key":"Si","value":""}}}]',
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 1,
				'systemOrder' => 3,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 5,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'text',
				'identifier' => 'telefon',
				'title' => 'Telefon',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => '[{"key":"","value":null,"_translations":{"de":{"value":""},"es":{"value":""}}}]',
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 4,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 6,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'email',
				'identifier' => 'email',
				'title' => 'E-Mail',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 1,
				'systemOrder' => 5,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 47,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'date',
				'identifier' => 'datum',
				'title' => 'Datum',
				'titleEmail' => null,
				'placeholder' => 'Datum bitte',
				'text' => null,
				'options' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 6,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 8,
				'formId' => 1,
				'parentId' => null,
				'type' => 'submit',
				'identifier' => null,
				'title' => 'Absenden',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => '[{"key":"","value":null,"_translations":{"de":{"value":""},"es":{"value":""}}}]',
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 7,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 48,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'time',
				'identifier' => 'uhrzeit',
				'title' => 'Uhrzeit',
				'titleEmail' => null,
				'placeholder' => 'Uhrzeit bitte',
				'text' => null,
				'options' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 7,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 49,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'datetime',
				'identifier' => 'datumUndUhrzeit',
				'title' => 'Datum und Uhrzeit',
				'titleEmail' => null,
				'placeholder' => 'Datum und Uhrzeit bitte',
				'text' => null,
				'options' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 8,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 50,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'checkbox',
				'identifier' => 'multiCheckbox',
				'title' => 'Multi Checkbox',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => '[{"key":null,"value":null,"_translations":{"de":{"key":"","value":""},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"a","value":"Label A"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"b","value":"Label B"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"","value":"Label C (kein Value)"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"Value D (kein Wert)","value":""},"es":{"key":"","value":""}}}]',
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 9,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 51,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'radio',
				'identifier' => 'multiRadio',
				'title' => 'Multi Radio',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => '[{"key":null,"value":null,"_translations":{"de":{"key":"a","value":"Label A"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"b","value":"Label B"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"","value":"Label C (kein Value)"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"Value D (kein Wert)","value":""},"es":{"key":"","value":""}}}]',
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 10,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 52,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'selectMultiple',
				'identifier' => 'multiSelect',
				'title' => 'Multi Select',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => '[{"key":null,"value":null,"_translations":{"de":{"key":"a","value":"Label A"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"b","value":"Label B"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"","value":"Label C (kein Value)"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"Value D (kein Wert)","value":""},"es":{"key":"","value":""}}}]',
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 11,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 53,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'select',
				'identifier' => 'select',
				'title' => 'Select',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => '[{"key":null,"value":null,"_translations":{"de":{"key":"","value":""},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"a","value":"Label A"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"b","value":"Label B"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"","value":"Label C (kein Value)"},"es":{"key":"","value":""}}},{"key":null,"value":null,"_translations":{"de":{"key":"Value D (kein Wert)","value":""},"es":{"key":"","value":""}}}]',
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 12,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 54,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'file',
				'identifier' => 'dateiupload',
				'title' => 'Dateiupload',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 13,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 55,
				'formId' => 1,
				'parentId' => 1,
				'type' => 'hidden',
				'identifier' => 'verstecktesFeld',
				'title' => 'Verstecktes Feld',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 14,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 56,
				'formId' => 2,
				'parentId' => null,
				'type' => 'freeText',
				'identifier' => null,
				'title' => null,
				'titleEmail' => null,
				'placeholder' => null,
				'text' => '<p>Form element with inline img tag</p><p><awyiss-responsive-image>{"mediaId":"4"}</awyiss-responsive-image></p><p>between two paragraphs</p>',
				'options' => null,
				'columnWidth' => '4/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 57,
				'formId' => 1,
				'parentId' => null,
				'type' => 'freeText',
				'identifier' => null,
				'title' => null,
				'titleEmail' => null,
				'placeholder' => null,
				'text' => '<p>Form element with inline img tag</p><p><awyiss-responsive-image>{"mediaId":"4"}</awyiss-responsive-image></p><p>between two paragraphs</p>',
				'options' => null,
				'columnWidth' => '4/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 0,
				'systemOrder' => 1,
				'active' => 0,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 58,
				'formId' => 4,
				'parentId' => null,
				'type' => 'email',
				'identifier' => 'email',
				'title' => 'E-Mail',
				'titleEmail' => null,
				'placeholder' => null,
				'text' => null,
				'options' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'required' => 1,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => '2020-02-02 02:02:02',
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
		];

		$table = $this->table('form_elements');
		$table->insert($data)->save();
	}
}
