<?php declare(strict_types=1);


use Migrations\BaseSeed;


/**
 * GlobalContents seed.
 */
class GlobalContentsCustomSeed extends BaseSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$data = [
			[
				'id' => 4,
				'identifier' => 'dummyNested',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<widget class="mceNonEditable" data-identifier="breadcrumbs" data-label="Breadcrumbs">{"includeHomepage":true,"includeCurrentPage":true,"showOnHomepage":false,"homepageId":""}</widget>',
				'link' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 0,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 1,
				'identifier' => 'dummyRowOverflow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p class="Textsize-LikeH4">Max Mustermann</p>
<p>Musterstraße 123<br>12345 Musterstadt</p>
<p>Telefon: <a href="tel:+491234567890"><strong>0123-456789-0</strong></a><br>E-Mail: <a href="mailto:max@mustermann.de">max@mustermann.de</a></p>',
				'link' => null,
				'columnWidth' => '2/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 2,
				'identifier' => 'dummyRowOverflow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p class="Textsize-LikeH4">Unsere &Ouml;ffnungszeiten</p>
<table> <tbody> <tr> <td>Montag &ndash; Freitag</td> <td><strong>08:00</strong> bis <strong>18:00 Uhr</strong></td> </tr> <tr> <td>Samstag &ndash; Sonntag</td> <td><strong>09:00</strong> bis <strong>14:00 Uhr</strong></td> </tr> </tbody> </table>
',
				'link' => null,
				'columnWidth' => '3/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 3,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 3,
				'identifier' => 'dummyRowOverflow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p class="Textsize-LikeH4">Max Mustermann</p>
<p>Musterstraße 123<br>12345 Musterstadt</p>
<p>Telefon: <a href="tel:+491234567890"><strong>0123-456789-0</strong></a><br>E-Mail: <a href="mailto:max@mustermann.de">max@mustermann.de</a></p>',
				'link' => null,
				'columnWidth' => '3/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 5,
				'identifier' => 'dummyRowOverflow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
<h5>Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</h5>
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
<p>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>',
				'link' => null,
				'columnWidth' => '3/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 6,
				'identifier' => 'dummyNested',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>',
				'link' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 7,
				'identifier' => 'dummyNested',
				'globalContentTemplateId' => 1,
				'parentId' => 4,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Child of inactive</p>',
				'link' => null,
				'columnWidth' => '2/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 8,
				'identifier' => 'dummyMultiRow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 2</p>',
				'link' => null,
				'columnWidth' => '3/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 9,
				'identifier' => 'dummyMultiRow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 1 - first (half indented) and last</p>',
				'link' => null,
				'columnWidth' => '1/2',
				'columnIndent' => '1/2',
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => '{"ak":"av","ck":"cv"}',
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 10,
				'identifier' => 'dummyMultiRow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 3 with widget</p><widget class="mceNonEditable" data-identifier="breadcrumbs" data-label="Breadcrumbs">{"includeHomepage":true,"includeCurrentPage":true,"showOnHomepage":false,"homepageId":""}</widget><p>And Text after Widget</p>',
				'link' => null,
				'columnWidth' => '2/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 3,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 11,
				'identifier' => 'dummyMultiRow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 4 (last in row)</p>',
				'link' => null,
				'columnWidth' => '1/4',
				'columnIndent' => null,
				'columnLast' => 1,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 4,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 12,
				'identifier' => 'dummyMultiRow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 5 (RTL)</p>',
				'link' => null,
				'columnWidth' => '1/4',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 1,
				'cssClass' => 'AdditionalClass',
				'data' => null,
				'formId' => null,
				'systemOrder' => 5,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 13,
				'identifier' => 'dummySingleRow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 2</p>',
				'link' => null,
				'columnWidth' => '1/2',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 14,
				'identifier' => 'dummySingleRow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 1</p>',
				'link' => null,
				'columnWidth' => '1/2',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 15,
				'identifier' => 'dummyNested',
				'globalContentTemplateId' => 1,
				'parentId' => 7,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Child of child of inactive</p>',
				'link' => null,
				'columnWidth' => '2/3',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 16,
				'identifier' => 'dummyNarrow',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Narrow</p>',
				'link' => null,
				'columnWidth' => '1/1',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 17,
				'identifier' => 'dummyNarrow',
				'globalContentTemplateId' => 1,
				'parentId' => 16,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Narrow</p>',
				'link' => null,
				'columnWidth' => '1/2',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 18,
				'identifier' => 'inlineImg',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Global Content with inline img tag</p><p><awyiss-responsive-image>{"mediaId":"4"}</awyiss-responsive-image></p><p>between two paragraphs</p>',
				'link' => null,
				'columnWidth' => '4/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 19,
				'identifier' => 'customTemplate',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Global Content with custom template</p>',
				'link' => null,
				'columnWidth' => '4/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => 2,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 20,
				'identifier' => 'customTemplate',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Global Content with custom template that sets a content row class</p>',
				'link' => null,
				'columnWidth' => '4/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 21,
				'identifier' => 'customTemplate',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Global Content with regular template</p>',
				'link' => null,
				'columnWidth' => '4/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 22,
				'identifier' => 'doubleInlineImg',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p><awyiss-responsive-image>{"mediaId":"4"}</awyiss-responsive-image></p><p>Global Content with two inline img</p><p><awyiss-responsive-image>{"mediaId":"2"}</awyiss-responsive-image></p>',
				'link' => null,
				'columnWidth' => '4/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 23,
				'identifier' => 'withSurvey',
				'globalContentTemplateId' => 1,
				'parentId' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '',
				'link' => null,
				'columnWidth' => '4/5',
				'columnIndent' => null,
				'columnLast' => 0,
				'columnRtl' => 0,
				'cssClass' => null,
				'data' => null,
				'formId' => null,
				'surveyId' => 3,
				'systemOrder' => 1,
				'active' => 0,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
		];

		$table = $this->table('global_contents');
		$table->insert($data)->save();
	}
}
