<?php declare(strict_types=1);


use Migrations\AbstractSeed;


/**
 * MediaCustomSeed seed.
 */
class MediaCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$data = [
			[
				'id' => 1,
				'mediaFolderId' => 1,
				'mimeType' => 'application/vnd-openxmlformats-officedocument-wordprocessingml-document',
				'name' => 'logo-awyiss.docx',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.docx',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 1,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 2,
				'mediaFolderId' => 1,
				'mimeType' => 'image/jpeg',
				'name' => 'logo-awyiss.jpg',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.jpg',
				'alt' => null,
				'width' => 1080,
				'height' => 1920,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 2,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 3,
				'mediaFolderId' => 1,
				'mimeType' => 'application/pdf',
				'name' => 'logo-awyiss.pdf',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.pdf',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 3,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 4,
				'mediaFolderId' => 1,
				'mimeType' => 'image/png',
				'name' => 'logo-awyiss.png',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.png',
				'alt' => null,
				'width' => 2560,
				'height' => 1440,
				'metaData' => null,
				'averageColor' => null,
				'preview' => -1,
				'webp' => 1,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 4,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 5,
				'mediaFolderId' => 1,
				'mimeType' => 'application/vnd-openxmlformats-officedocument-presentationml-presentation',
				'name' => 'logo-awyiss.pptx',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.pptx',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 5,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 6,
				'mediaFolderId' => 1,
				'mimeType' => 'application/x-photoshop',
				'name' => 'logo-awyiss.psd',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.psd',
				'alt' => null,
				'width' => 1440,
				'height' => 900,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 6,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 7,
				'mediaFolderId' => 1,
				'mimeType' => 'image/svg+xml',
				'name' => 'logo-awyiss.svg',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.svg',
				'alt' => null,
				'width' => 2000,
				'height' => 1000,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 7,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 8,
				'mediaFolderId' => 1,
				'mimeType' => 'application/vnd-openxmlformats-officedocument-spreadsheetml-sheet',
				'name' => 'logo-awyiss.xlsx',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.xlsx',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 8,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 9,
				'mediaFolderId' => 1,
				'mimeType' => 'application/unknown',
				'name' => 'logo-awyiss.unknown',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.unknown',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 8,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 10,
				'mediaFolderId' => 1,
				'mimeType' => 'image/jpeg',
				'name' => 'logo-awyiss2.jpg',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss2.jpg',
				'alt' => null,
				'width' => 1080,
				'height' => 1920,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 9,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 11,
				'mediaFolderId' => 1,
				'mimeType' => 'video/mp4',
				'name' => 'multimedia-test.mp4',
				'path' => '../awyiss/Command/Media/TestFiles/multimedia-test.mp4',
				'alt' => null,
				'width' => 1920,
				'height' => 1080,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 10,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 12,
				'mediaFolderId' => 1,
				'mimeType' => 'video/webm',
				'name' => 'multimedia-test.webm',
				'path' => '../awyiss/Command/Media/TestFiles/multimedia-test.webm',
				'alt' => null,
				'width' => 1920,
				'height' => 1080,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 11,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 13,
				'mediaFolderId' => 1,
				'mimeType' => 'text/vtt',
				'name' => 'multimedia-test-de.vtt',
				'path' => '../awyiss/Command/Media/TestFiles/multimedia-test-de.vtt',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 12,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 14,
				'mediaFolderId' => 1,
				'mimeType' => 'text/vtt',
				'name' => 'multimedia-test-en.vtt',
				'path' => '../awyiss/Command/Media/TestFiles/multimedia-test-en.vtt',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 13,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 15,
				'mediaFolderId' => 1,
				'mimeType' => 'audio/mpeg',
				'name' => 'multimedia-test.mp3',
				'path' => '../awyiss/Command/Media/TestFiles/multimedia-test.mp3',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 14,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 16,
				'mediaFolderId' => 1,
				'mimeType' => 'audio/ogg',
				'name' => 'multimedia-test.ogg',
				'path' => '../awyiss/Command/Media/TestFiles/multimedia-test.ogg',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 15,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 17,
				'mediaFolderId' => 1,
				'mimeType' => 'audio/ogg',
				'name' => 'multimedia-test-no-other-source.ogg',
				'path' => '../awyiss/Command/Media/TestFiles/multimedia-test-no-other-source.ogg',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 16,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 18,
				'mediaFolderId' => 1,
				'mimeType' => 'video/webm',
				'name' => 'multimedia-test-no-other-source.webm',
				'path' => '../awyiss/Command/Media/TestFiles/multimedia-test-no-other-source.webm',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 17,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 19,
				'mediaFolderId' => 1,
				'mimeType' => 'audio/mpeg',
				'name' => 'audio-test.mp3',
				'path' => '../awyiss/Command/Media/TestFiles/audio-test.mp3',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 18,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 20,
				'mediaFolderId' => 1,
				'mimeType' => 'audio/ogg',
				'name' => 'audio-test.ogg',
				'path' => '../awyiss/Command/Media/TestFiles/audio-test.ogg',
				'alt' => null,
				'width' => null,
				'height' => null,
				'metaData' => null,
				'averageColor' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focusPoint' => null,
				'systemOrder' => 19,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
		];

		$table = $this->table('media');
		$table->truncate();
		$table->insert($data)->save();
	}
}
