<?php declare(strict_types=1);


use Migrations\AbstractSeed;


/**
 * MediaAssignmentsCustomSeed seed.
 */
class MediaAssignmentsCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$data = [
			[
				'id' => 1,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'GlobalContents',
				'foreignKey' => 4,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 2,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'lightboxMedia',
				'mediaId' => 3,
				'mediaFolderId' => null,
				'scope' => 'GlobalContents',
				'foreignKey' => 4,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 3,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 2,
				'mediaFolderId' => null,
				'scope' => 'GlobalContents',
				'foreignKey' => 6,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 4,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 2,
				'mediaFolderId' => null,
				'scope' => 'GlobalContents',
				'foreignKey' => 7,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 5,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 2,
				'mediaFolderId' => null,
				'scope' => 'GlobalContents',
				'foreignKey' => 16,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 6,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 18,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 7,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'lightboxMedia',
				'mediaId' => 3,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 18,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 8,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 2,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 2,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 9,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 2,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 16,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 10,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 2,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 39,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 11,
				'mediaElementId' => 1,
				'mediaElementSelectorIdentifier' => 'hiddenFolder',
				'mediaId' => null,
				'mediaFolderId' => 1,
				'scope' => 'News',
				'foreignKey' => 21,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 12,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 2,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 44,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 13,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'GlobalContents',
				'foreignKey' => 18,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 14,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'SurveyQuestions',
				'foreignKey' => 3,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 15,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'FormElements',
				'foreignKey' => 56,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 16,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'Forms',
				'foreignKey' => 1,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 17,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 45,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 18,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'Surveys',
				'foreignKey' => 3,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 19,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'FormElements',
				'foreignKey' => 57,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 20,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'News',
				'foreignKey' => 38,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 21,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 2,
				'mediaFolderId' => null,
				'scope' => 'GlobalContents',
				'foreignKey' => 18,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 22,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 2,
				'mediaFolderId' => null,
				'scope' => 'GlobalContents',
				'foreignKey' => 22,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 23,
				'mediaElementId' => 5,
				'mediaElementSelectorIdentifier' => 'inlineImgTag',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'GlobalContents',
				'foreignKey' => 22,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 26,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 47,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 27,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 45,
				'systemOrder' => 1,
				'deleted' => 0,
			],
			[
				'id' => 30,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 7,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 54,
				'systemOrder' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 31,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'lightboxMedia',
				'mediaId' => 7,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 54,
				'systemOrder' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 32,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 6,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 55,
				'systemOrder' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 33,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'lightboxMedia',
				'mediaId' => 6,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 55,
				'systemOrder' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 34,
				'mediaElementId' => 2,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 10,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 57,
				'systemOrder' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 35,
				'mediaElementId' => 4,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 2,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 57,
				'systemOrder' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 36,
				'mediaElementId' => 4,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 4,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 57,
				'systemOrder' => 2,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 37,
				'mediaElementId' => 4,
				'mediaElementSelectorIdentifier' => 'media',
				'mediaId' => 10,
				'mediaFolderId' => null,
				'scope' => 'Contents',
				'foreignKey' => 57,
				'systemOrder' => 3,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
		];

		$table = $this->table('media_assignments');
		$table->truncate();
		$table->insert($data)->save();
	}
}
