<?php declare(strict_types=1);


use Migrations\AbstractSeed;


/**
 * MediaResizedImagesCustomSeed seed.
 */
class MediaResizedImagesCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$data = [
			[
				'id' => 1,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w1024].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w1024].webp',
				'width' => 1024,
				'height' => null,
				'realWidth' => 1024,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 2,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w768].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w768].webp',
				'width' => 768,
				'height' => null,
				'realWidth' => 768,
				'realHeight' => 640,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 3,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w2560].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w2560].webp',
				'width' => 2560,
				'height' => null,
				'realWidth' => 2560,
				'realHeight' => 1440,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 4,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w640].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w640].webp',
				'width' => 640,
				'height' => null,
				'realWidth' => 640,
				'realHeight' => 360,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 5,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w480].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w480].webp',
				'width' => 480,
				'height' => null,
				'realWidth' => 480,
				'realHeight' => 270,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 6,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w320].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w320].webp',
				'width' => 320,
				'height' => null,
				'realWidth' => 320,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 7,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w1440].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w1440].webp',
				'width' => 1440,
				'height' => null,
				'realWidth' => 1440,
				'realHeight' => 810,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 8,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w576].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w576].webp',
				'width' => 576,
				'height' => null,
				'realWidth' => 576,
				'realHeight' => 324,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 9,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w1024].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w1024].avif',
				'width' => 1024,
				'height' => null,
				'realWidth' => 1024,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 10,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w768].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w768].avif',
				'width' => 768,
				'height' => null,
				'realWidth' => 768,
				'realHeight' => 640,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 11,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w2560].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w2560].avif',
				'width' => 2560,
				'height' => null,
				'realWidth' => 2560,
				'realHeight' => 1440,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 12,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w640].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w640].avif',
				'width' => 640,
				'height' => null,
				'realWidth' => 640,
				'realHeight' => 360,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 13,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w480].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w480].avif',
				'width' => 480,
				'height' => null,
				'realWidth' => 480,
				'realHeight' => 270,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 14,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w320].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w320].avif',
				'width' => 320,
				'height' => null,
				'realWidth' => 320,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 15,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w1440].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w1440].avif',
				'width' => 1440,
				'height' => null,
				'realWidth' => 1440,
				'realHeight' => 810,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 16,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[w576].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w576].avif',
				'width' => 576,
				'height' => null,
				'realWidth' => 576,
				'realHeight' => 324,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 17,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[1280].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w1280].webp',
				'width' => 1280,
				'height' => null,
				'realWidth' => 1280,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 18,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[1152].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w1152].webp',
				'width' => 1152,
				'height' => null,
				'realWidth' => 1152,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 19,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[925].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w925].webp',
				'width' => 925,
				'height' => null,
				'realWidth' => 925,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 20,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[1920].webp',
				'path' => '_resized/dummypath/logo-awyiss-[w1920].webp',
				'width' => 1920,
				'height' => null,
				'realWidth' => 1920,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 21,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[1280].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w1280].avif',
				'width' => 1280,
				'height' => null,
				'realWidth' => 1280,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 22,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[1152].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w1152].avif',
				'width' => 1152,
				'height' => null,
				'realWidth' => 1152,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 23,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[925].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w925].avif',
				'width' => 925,
				'height' => null,
				'realWidth' => 925,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 24,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[1920].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w1920].avif',
				'width' => 1920,
				'height' => null,
				'realWidth' => 1920,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 25,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[2048].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w2048].avif',
				'width' => 2048,
				'height' => null,
				'realWidth' => 2048,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 26,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[1536].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w1536].avif',
				'width' => 1536,
				'height' => null,
				'realWidth' => 1536,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
			[
				'id' => 27,
				'mediaId' => 4,
				'name' => 'logo-awyiss-[1728].avif',
				'path' => '_resized/dummypath/logo-awyiss-[w1728].avif',
				'width' => 1728,
				'height' => null,
				'realWidth' => 1728,
				'realHeight' => null,
				'strategy' => 1,
				'status' => 1,
			],
		];

		$table = $this->table('media_resized_images');
		$table->truncate();
		$table->insert($data)->save();
	}
}
