<?php declare(strict_types=1);


use Migrations\AbstractSeed;


/**
 * MediaCustomSeed seed.
 */
class MediaCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$la_data = [
			[
				'id' => 1,
				'media_folder_id' => 1,
				'mime_type' => 'application/vnd-openxmlformats-officedocument-wordprocessingml-document',
				'name' => 'logo-awyiss.docx',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.docx',
				'alt' => null,
				'width' => null,
				'height' => null,
				'meta_data' => null,
				'average_color' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focus_point' => null,
				'system_order' => 1,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 2,
				'media_folder_id' => 1,
				'mime_type' => 'image/jpeg',
				'name' => 'logo-awyiss.jpg',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.jpg',
				'alt' => null,
				'width' => 1080,
				'height' => 1920,
				'meta_data' => null,
				'average_color' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focus_point' => null,
				'system_order' => 2,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 3,
				'media_folder_id' => 1,
				'mime_type' => 'application/pdf',
				'name' => 'logo-awyiss.pdf',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.pdf',
				'alt' => null,
				'width' => null,
				'height' => null,
				'meta_data' => null,
				'average_color' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focus_point' => null,
				'system_order' => 3,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 4,
				'media_folder_id' => 1,
				'mime_type' => 'image/png',
				'name' => 'logo-awyiss.png',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.png',
				'alt' => null,
				'width' => 2560,
				'height' => 1440,
				'meta_data' => null,
				'average_color' => null,
				'preview' => -1,
				'webp' => 1,
				'crop' => null,
				'focus_point' => null,
				'system_order' => 4,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 5,
				'media_folder_id' => 1,
				'mime_type' => 'application/vnd-openxmlformats-officedocument-presentationml-presentation',
				'name' => 'logo-awyiss.pptx',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.pptx',
				'alt' => null,
				'width' => null,
				'height' => null,
				'meta_data' => null,
				'average_color' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focus_point' => null,
				'system_order' => 5,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 6,
				'media_folder_id' => 1,
				'mime_type' => 'application/x-photoshop',
				'name' => 'logo-awyiss.psd',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.psd',
				'alt' => null,
				'width' => 1440,
				'height' => 900,
				'meta_data' => null,
				'average_color' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focus_point' => null,
				'system_order' => 6,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 7,
				'media_folder_id' => 1,
				'mime_type' => 'image/svg+xml',
				'name' => 'logo-awyiss.svg',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.svg',
				'alt' => null,
				'width' => 2000,
				'height' => 1000,
				'meta_data' => null,
				'average_color' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focus_point' => null,
				'system_order' => 7,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 8,
				'media_folder_id' => 1,
				'mime_type' => 'application/vnd-openxmlformats-officedocument-spreadsheetml-sheet',
				'name' => 'logo-awyiss.xlsx',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.xlsx',
				'alt' => null,
				'width' => null,
				'height' => null,
				'meta_data' => null,
				'average_color' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focus_point' => null,
				'system_order' => 8,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 9,
				'media_folder_id' => 1,
				'mime_type' => 'application/unknown',
				'name' => 'logo-awyiss.unknown',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss.unknown',
				'alt' => null,
				'width' => null,
				'height' => null,
				'meta_data' => null,
				'average_color' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focus_point' => null,
				'system_order' => 8,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 10,
				'media_folder_id' => 1,
				'mime_type' => 'image/jpeg',
				'name' => 'logo-awyiss2.jpg',
				'path' => '../awyiss/Command/Media/TestFiles/logo-awyiss2.jpg',
				'alt' => null,
				'width' => 1080,
				'height' => 1920,
				'meta_data' => null,
				'average_color' => null,
				'preview' => 0,
				'webp' => 0,
				'crop' => null,
				'focus_point' => null,
				'system_order' => 9,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
		];

		$lo_table = $this->table('media');
		$lo_table->truncate();
		$lo_table->insert($la_data)->save();
	}
}
