<?php declare(strict_types=1);


use Migrations\AbstractSeed;


/**
 * MediaAssignmentsCustomSeed seed.
 */
class MediaAssignmentsCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$data = [
			[
				'id' => 1,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'widgets',
				'foreign_key' => 4,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 2,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'lightbox_media',
				'media_id' => 3,
				'media_folder_id' => null,
				'scope' => 'widgets',
				'foreign_key' => 4,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 3,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 2,
				'media_folder_id' => null,
				'scope' => 'widgets',
				'foreign_key' => 6,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 4,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 2,
				'media_folder_id' => null,
				'scope' => 'widgets',
				'foreign_key' => 7,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 5,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 2,
				'media_folder_id' => null,
				'scope' => 'widgets',
				'foreign_key' => 16,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 6,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 18,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 7,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'lightbox_media',
				'media_id' => 3,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 18,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 8,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 2,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 2,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 9,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 2,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 16,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 10,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 2,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 39,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 11,
				'media_element_id' => 1,
				'media_element_selector_identifier' => 'hidden_folder',
				'media_id' => null,
				'media_folder_id' => 1,
				'scope' => 'news',
				'foreign_key' => 21,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 12,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 2,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 44,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 13,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'widgets',
				'foreign_key' => 18,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 14,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'survey_questions',
				'foreign_key' => 3,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 15,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'form_elements',
				'foreign_key' => 56,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 16,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'forms',
				'foreign_key' => 1,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 17,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 45,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 18,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'surveys',
				'foreign_key' => 3,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 19,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'form_elements',
				'foreign_key' => 57,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 20,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'news',
				'foreign_key' => 38,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 21,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 2,
				'media_folder_id' => null,
				'scope' => 'widgets',
				'foreign_key' => 18,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 22,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 2,
				'media_folder_id' => null,
				'scope' => 'widgets',
				'foreign_key' => 22,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 23,
				'media_element_id' => 5,
				'media_element_selector_identifier' => 'inline_img_tag',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'widgets',
				'foreign_key' => 22,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 26,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 47,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 27,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 45,
				'system_order' => 1,
				'deleted' => 0,
			],
			[
				'id' => 30,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 7,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 54,
				'system_order' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 31,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'lightbox_media',
				'media_id' => 7,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 54,
				'system_order' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 32,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 6,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 55,
				'system_order' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 33,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'lightbox_media',
				'media_id' => 6,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 55,
				'system_order' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 34,
				'media_element_id' => 2,
				'media_element_selector_identifier' => 'media',
				'media_id' => 10,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 57,
				'system_order' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 35,
				'media_element_id' => 4,
				'media_element_selector_identifier' => 'media',
				'media_id' => 2,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 57,
				'system_order' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 36,
				'media_element_id' => 4,
				'media_element_selector_identifier' => 'media',
				'media_id' => 4,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 57,
				'system_order' => 2,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 37,
				'media_element_id' => 4,
				'media_element_selector_identifier' => 'media',
				'media_id' => 10,
				'media_folder_id' => null,
				'scope' => 'contents',
				'foreign_key' => 57,
				'system_order' => 3,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
		];

		$table = $this->table('media_assignments');
		$table->truncate();
		$table->insert($data)->save();
	}
}
