<?php declare(strict_types=1);


use Migrations\AbstractSeed;


/**
 * MenuEntries seed.
 */
class MenuEntriesCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$la_data = [
			[
				'id' => 1,
				'menu_id' => 2,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Dienstleistungen',
				'link' => 'de/dienstleistungen',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 2,
				'menu_id' => 2,
				'parent_id' => 1,
				'language_shortcode' => 'de',
				'title' => 'Seefracht',
				'link' => 'de/dienstleistungen/seefracht',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 7,
				'menu_id' => 2,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Über uns',
				'link' => 'de/ueber-uns',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 8,
				'menu_id' => 2,
				'parent_id' => 7,
				'language_shortcode' => 'de',
				'title' => 'Unternehmensgeschichte',
				'link' => 'de/ueber-uns/unternehmensgeschichte',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 13,
				'menu_id' => 4,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Instagram',
				'link' => 'https://www.instagram.com/',
				'external' => 1,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 18,
				'menu_id' => 3,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Kontakt',
				'link' => 'de/kontakt',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 20,
				'menu_id' => 1,
				'parent_id' => 19,
				'language_shortcode' => 'de',
				'title' => 'Unternehmensgeschichte',
				'link' => 'de/ueber-uns/unternehmensgeschichte',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 25,
				'menu_id' => 1,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Dienstleistungen',
				'link' => 'de/dienstleistungen',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 26,
				'menu_id' => 1,
				'parent_id' => 25,
				'language_shortcode' => 'de',
				'title' => 'Seefracht',
				'link' => 'de/dienstleistungen/seefracht',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 32,
				'menu_id' => 1,
				'parent_id' => 31,
				'language_shortcode' => 'de',
				'title' => 'Übersicht der Schiffe',
				'link' => 'de/flotte/uebersicht-der-schiffe',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 37,
				'menu_id' => 1,
				'parent_id' => 36,
				'language_shortcode' => 'de',
				'title' => 'Anmeldung/Registrierung',
				'link' => 'de/kundenbereich/registrierung',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 42,
				'menu_id' => 1,
				'parent_id' => 41,
				'language_shortcode' => 'de',
				'title' => 'Offene Stellen',
				'link' => 'de/karriere/offene-stellen',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 3,
				'menu_id' => 2,
				'parent_id' => 1,
				'language_shortcode' => 'de',
				'title' => 'Luftfracht',
				'link' => 'de/dienstleistungen/luftfracht',
				'external' => 0,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 9,
				'menu_id' => 2,
				'parent_id' => 7,
				'language_shortcode' => 'de',
				'title' => 'Mission und Vision',
				'link' => 'de/ueber-uns/mission-und-vision',
				'external' => 0,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 14,
				'menu_id' => 4,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Facebook',
				'link' => 'https://www.facebook.com/',
				'external' => 1,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 16,
				'menu_id' => 3,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Impressum',
				'link' => 'de/impressum',
				'external' => 0,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 21,
				'menu_id' => 1,
				'parent_id' => 19,
				'language_shortcode' => 'de',
				'title' => 'Mission und Vision',
				'link' => 'de/ueber-uns/mission-und-vision',
				'external' => 0,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 27,
				'menu_id' => 1,
				'parent_id' => 25,
				'language_shortcode' => 'de',
				'title' => 'Luftfracht',
				'link' => 'de/dienstleistungen/luftfracht',
				'external' => 0,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 31,
				'menu_id' => 1,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Flotte',
				'link' => 'de/flotte',
				'external' => 0,
				'system_order' => 2,
				'active' => 0,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 33,
				'menu_id' => 1,
				'parent_id' => 31,
				'language_shortcode' => 'de',
				'title' => 'Technische Daten',
				'link' => 'de/flotte/technische-daten',
				'external' => 0,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 38,
				'menu_id' => 1,
				'parent_id' => 36,
				'language_shortcode' => 'de',
				'title' => 'Sendungsverfolgung',
				'link' => 'de/kundenbereich/sendungsverfolgung',
				'external' => 0,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 43,
				'menu_id' => 1,
				'parent_id' => 41,
				'language_shortcode' => 'de',
				'title' => 'Ausbildungsprogramme',
				'link' => 'de/karriere/ausbildungsprogramme',
				'external' => 0,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 4,
				'menu_id' => 2,
				'parent_id' => 1,
				'language_shortcode' => 'de',
				'title' => 'Landtransport',
				'link' => 'de/dienstleistungen/landtransport',
				'external' => 0,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 10,
				'menu_id' => 2,
				'parent_id' => 7,
				'language_shortcode' => 'de',
				'title' => 'Teamvorstellung',
				'link' => 'de/ueber-uns/teamvorstellung',
				'external' => 0,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 15,
				'menu_id' => 4,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Xing',
				'link' => 'https://www.xing.com',
				'external' => 1,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 17,
				'menu_id' => 3,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Datenschutzrichtlinien',
				'link' => 'de/datenschutzrichtlinien',
				'external' => 0,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 19,
				'menu_id' => 1,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Über uns',
				'link' => 'de/ueber-uns',
				'external' => 0,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 22,
				'menu_id' => 1,
				'parent_id' => 19,
				'language_shortcode' => 'de',
				'title' => 'Teamvorstellung',
				'link' => 'de/ueber-uns/teamvorstellung',
				'external' => 0,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 28,
				'menu_id' => 1,
				'parent_id' => 25,
				'language_shortcode' => 'de',
				'title' => 'Landtransport',
				'link' => 'de/dienstleistungen/landtransport',
				'external' => 0,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 34,
				'menu_id' => 1,
				'parent_id' => 31,
				'language_shortcode' => 'de',
				'title' => 'Sicherheitsstandards',
				'link' => 'de/flotte/sicherheitsstandards',
				'external' => 0,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 39,
				'menu_id' => 1,
				'parent_id' => 36,
				'language_shortcode' => 'de',
				'title' => 'Dokumentenverwaltung',
				'link' => 'de/kundenbereich/dokumentenverwaltung',
				'external' => 0,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 44,
				'menu_id' => 1,
				'parent_id' => 41,
				'language_shortcode' => 'de',
				'title' => 'Mitarbeiterbenefits',
				'link' => 'de/karriere/mitarbeiterbenefits',
				'external' => 0,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 5,
				'menu_id' => 2,
				'parent_id' => 1,
				'language_shortcode' => 'de',
				'title' => 'Lagerung und Logistik',
				'link' => 'de/dienstleistungen/lagerung-und-logistik',
				'external' => 0,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 11,
				'menu_id' => 2,
				'parent_id' => 7,
				'language_shortcode' => 'de',
				'title' => 'Zertifikate',
				'link' => 'de/ueber-uns/zertifikate-und-auszeichnungen',
				'external' => 0,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => 1,
				'changed_on' => '2024-08-24 17:51:00',
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 23,
				'menu_id' => 1,
				'parent_id' => 19,
				'language_shortcode' => 'de',
				'title' => 'Zertifikate und Auszeichnungen',
				'link' => 'de/ueber-uns/zertifikate-und-auszeichnungen',
				'external' => 0,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 29,
				'menu_id' => 1,
				'parent_id' => 25,
				'language_shortcode' => 'de',
				'title' => 'Lagerung und Logistik',
				'link' => 'de/dienstleistungen/lagerung-und-logistik',
				'external' => 0,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 35,
				'menu_id' => 1,
				'parent_id' => 31,
				'language_shortcode' => 'de',
				'title' => 'Umweltfreundlichkeit',
				'link' => 'de/flotte/umweltfreundlichkeit',
				'external' => 0,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 36,
				'menu_id' => 1,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Kundenbereich',
				'link' => 'de/kundenbereich',
				'external' => 0,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 40,
				'menu_id' => 1,
				'parent_id' => 36,
				'language_shortcode' => 'de',
				'title' => 'Rechnungsübersicht',
				'link' => 'de/kundenbereich/rechnungsuebersicht',
				'external' => 0,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 45,
				'menu_id' => 1,
				'parent_id' => 41,
				'language_shortcode' => 'de',
				'title' => 'Bewerbungsprozess',
				'link' => 'de/karriere/bewerbungsprozess',
				'external' => 0,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 6,
				'menu_id' => 2,
				'parent_id' => 1,
				'language_shortcode' => 'de',
				'title' => 'Zollabwicklung',
				'link' => 'de/dienstleistungen/zollabwicklung',
				'external' => 0,
				'system_order' => 5,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 12,
				'menu_id' => 2,
				'parent_id' => 7,
				'language_shortcode' => 'de',
				'title' => 'Aktuelles',
				'link' => 'de/ueber-uns/aktuelles',
				'external' => 0,
				'system_order' => 5,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 24,
				'menu_id' => 1,
				'parent_id' => 19,
				'language_shortcode' => 'de',
				'title' => 'Aktuelles',
				'link' => 'de/ueber-uns/aktuelles',
				'external' => 0,
				'system_order' => 5,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 30,
				'menu_id' => 1,
				'parent_id' => 25,
				'language_shortcode' => 'de',
				'title' => 'Zollabwicklung mit <strong>Auszeichung</strong> und <script>alert(\'Script\');</script>',
				'link' => 'de/dienstleistungen/zollabwicklung',
				'external' => 0,
				'system_order' => 5,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 41,
				'menu_id' => 1,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Karriere',
				'link' => 'de/karriere',
				'external' => 0,
				'system_order' => 5,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 46,
				'menu_id' => 1,
				'parent_id' => null,
				'language_shortcode' => 'de',
				'title' => 'Kontakt',
				'link' => 'de/kontakt',
				'external' => 0,
				'system_order' => 6,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 47,
				'menu_id' => 1,
				'parent_id' => null,
				'language_shortcode' => 'it',
				'title' => 'Home',
				'link' => 'it/home',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 48,
				'menu_id' => 1,
				'parent_id' => null,
				'language_shortcode' => 'it',
				'title' => 'Servizi',
				'link' => 'it/servizi',
				'external' => 0,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 49,
				'menu_id' => 1,
				'parent_id' => 48,
				'language_shortcode' => 'it',
				'title' => 'Trasporto Marittimo',
				'link' => 'it/servizi/trasporto-marittimo',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 50,
				'menu_id' => 1,
				'parent_id' => 48,
				'language_shortcode' => 'it',
				'title' => 'Trasporto Aereo',
				'link' => 'it/servizi/trasporto-aereo',
				'external' => 0,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 51,
				'menu_id' => 1,
				'parent_id' => null,
				'language_shortcode' => 'it',
				'title' => 'Chi Siamo',
				'link' => 'it/chi-siamo',
				'external' => 0,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 52,
				'menu_id' => 1,
				'parent_id' => 51,
				'language_shortcode' => 'it',
				'title' => 'La Nostra Storia',
				'link' => 'it/chi-siamo/la-nostra-storia',
				'external' => 0,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 53,
				'menu_id' => 1,
				'parent_id' => null,
				'language_shortcode' => 'it',
				'title' => 'Contatti',
				'link' => 'it/contatti',
				'external' => 0,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
		];

		$lo_table = $this->table('menu_entries');
		$lo_table->insert($la_data)->save();
	}
}
