<?php declare(strict_types=1);


use Migrations\BaseSeed;


/**
 * SurveySurveyAnswers seed.
 */
class SurveySurveyAnswersCustomSeed extends BaseSeed {
	/**
	 * {@inheritDoc}
	 */
	public function run(): void {
		$data = [
			[
				'id' => 4,
				'surveyAnswerId' => 1,
				'surveySurveyQuestionId' => 2,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => null,
				'nextActionTarget' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 7,
				'surveyAnswerId' => 4,
				'surveySurveyQuestionId' => 3,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => null,
				'nextActionTarget' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 10,
				'surveyAnswerId' => 7,
				'surveySurveyQuestionId' => 6,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => null,
				'nextActionTarget' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 5,
				'surveyAnswerId' => 2,
				'surveySurveyQuestionId' => 2,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'specificQuestion',
				'nextActionTarget' => '0194a883',
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 8,
				'surveyAnswerId' => 5,
				'surveySurveyQuestionId' => 3,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => null,
				'nextActionTarget' => null,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 11,
				'surveyAnswerId' => 8,
				'surveySurveyQuestionId' => 6,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => null,
				'nextActionTarget' => null,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 6,
				'surveyAnswerId' => 3,
				'surveySurveyQuestionId' => 2,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'specificQuestion',
				'nextActionTarget' => '72054f17',
				'systemOrder' => 3,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 9,
				'surveyAnswerId' => 6,
				'surveySurveyQuestionId' => 3,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => null,
				'nextActionTarget' => null,
				'systemOrder' => 3,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 12,
				'surveyAnswerId' => 9,
				'surveySurveyQuestionId' => 6,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'specificQuestion',
				'nextActionTarget' => 'e5f3b6a9',
				'systemOrder' => 3,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 13,
				'surveyAnswerId' => 8,
				'surveySurveyQuestionId' => 7,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => null,
				'nextActionTarget' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 14,
				'surveyAnswerId' => 9,
				'surveySurveyQuestionId' => 7,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'abort',
				'nextActionTarget' => null,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 15,
				'surveyAnswerId' => 10,
				'surveySurveyQuestionId' => 6,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'abort',
				'nextActionTarget' => null,
				'systemOrder' => 2,
				'active' => 0,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 16,
				'surveyAnswerId' => 8,
				'surveySurveyQuestionId' => 8,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => null,
				'nextActionTarget' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 17,
				'surveyAnswerId' => 9,
				'surveySurveyQuestionId' => 8,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => null,
				'nextActionTarget' => null,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
		];

		$table = $this->table('survey_survey_answers');
		$table->insert($data)->save();
	}
}
