<?php declare(strict_types=1);


use Migrations\BaseSeed;


/**
 * SurveySurveyAnswers seed.
 */
class SurveySurveyAnswersCustomSeed extends BaseSeed {
	/**
	 * {@inheritDoc}
	 */
	public function run(): void {
		$la_data = [
			[
				'id' => 4,
				'survey_answer_id' => 1,
				'survey_survey_question_id' => 2,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'next_action' => null,
				'next_action_target' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 7,
				'survey_answer_id' => 4,
				'survey_survey_question_id' => 3,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'next_action' => null,
				'next_action_target' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 10,
				'survey_answer_id' => 7,
				'survey_survey_question_id' => 6,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'next_action' => null,
				'next_action_target' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 5,
				'survey_answer_id' => 2,
				'survey_survey_question_id' => 2,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'next_action' => 'specific_question',
				'next_action_target' => '0194a883',
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 8,
				'survey_answer_id' => 5,
				'survey_survey_question_id' => 3,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'next_action' => null,
				'next_action_target' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 11,
				'survey_answer_id' => 8,
				'survey_survey_question_id' => 6,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'next_action' => null,
				'next_action_target' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 6,
				'survey_answer_id' => 3,
				'survey_survey_question_id' => 2,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'next_action' => 'specific_question',
				'next_action_target' => '72054f17',
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 9,
				'survey_answer_id' => 6,
				'survey_survey_question_id' => 3,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'next_action' => null,
				'next_action_target' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 12,
				'survey_answer_id' => 9,
				'survey_survey_question_id' => 6,
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'next_action' => null,
				'next_action_target' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
		];

		$lo_table = $this->table('survey_survey_answers');
		$lo_table->insert($la_data)->save();
	}
}
