<?php declare(strict_types=1);


use Migrations\BaseSeed;


/**
 * SurveySurveyQuestions seed.
 */
class SurveySurveyQuestionsCustomSeed extends BaseSeed {
	/**
	 * {@inheritDoc}
	 */
	public function run(): void {
		$data = [
			[
				'id' => 2,
				'surveyId' => 1,
				'surveyQuestionId' => 1,
				'identifier' => '8524de5e',
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'nextQuestion',
				'nextActionTarget' => null,
				'allowCustomAnswer' => 0,
				'customAnswerTitle' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 3,
				'surveyId' => 1,
				'surveyQuestionId' => 2,
				'identifier' => 'f69b1648',
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'nextQuestion',
				'nextActionTarget' => null,
				'allowCustomAnswer' => 0,
				'customAnswerTitle' => null,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 4,
				'surveyId' => 1,
				'surveyQuestionId' => 3,
				'identifier' => '0194a883',
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'nextQuestion',
				'nextActionTarget' => null,
				'allowCustomAnswer' => null,
				'customAnswerTitle' => null,
				'systemOrder' => 3,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 5,
				'surveyId' => 1,
				'surveyQuestionId' => 4,
				'identifier' => '7d654446',
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'nextQuestion',
				'nextActionTarget' => null,
				'allowCustomAnswer' => null,
				'customAnswerTitle' => null,
				'systemOrder' => 4,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 6,
				'surveyId' => 1,
				'surveyQuestionId' => 5,
				'identifier' => '72054f17',
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'nextQuestion',
				'nextActionTarget' => null,
				'allowCustomAnswer' => 0,
				'customAnswerTitle' => null,
				'systemOrder' => 5,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 7,
				'surveyId' => 3,
				'surveyQuestionId' => 5,
				'identifier' => '9f8b2c3d',
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'nextQuestion',
				'nextActionTarget' => null,
				'allowCustomAnswer' => 0,
				'customAnswerTitle' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 8,
				'surveyId' => 4,
				'surveyQuestionId' => 5,
				'identifier' => 'c3b2a1e4',
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'nextQuestion',
				'nextActionTarget' => null,
				'allowCustomAnswer' => 0,
				'customAnswerTitle' => null,
				'systemOrder' => 1,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 9,
				'surveyId' => 4,
				'surveyQuestionId' => 3,
				'identifier' => 'da147ac8',
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'abort',
				'nextActionTarget' => null,
				'allowCustomAnswer' => 0,
				'customAnswerTitle' => null,
				'systemOrder' => 2,
				'active' => 1,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
			[
				'id' => 10,
				'surveyId' => 1,
				'surveyQuestionId' => 2,
				'identifier' => 'e5f3b6a9',
				'title' => null,
				'subtitle' => null,
				'text' => null,
				'nextAction' => 'abort',
				'nextActionTarget' => null,
				'allowCustomAnswer' => 0,
				'customAnswerTitle' => null,
				'systemOrder' => 6,
				'active' => 0,
				'deleted' => 0,
				'createdBy' => 1,
				'createdOn' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changedBy' => null,
				'changedOn' => null,
				'deletedBy' => null,
				'deletedOn' => null,
			],
		];

		$table = $this->table('survey_survey_questions');
		$table->insert($data)->save();
	}
}
