<?php declare(strict_types=1);


use Migrations\AbstractSeed;


/**
 * Widgets seed.
 */
class WidgetsCustomSeed extends AbstractSeed {
	/**
	 * @inheritDoc
	 */
	public function run(): void {
		$la_data = [
			[
				'id' => 4,
				'identifier' => 'dummy_nested',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<module class="mceNonEditable" data-identifier="breadcrumbs" data-label="Breadcrumbs">{"includeHomepage":true,"includeCurrentPage":true,"showOnHomepage":false,"homepageId":""}</module>',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 0,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 1,
				'identifier' => 'dummy_row_overflow',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p class="Textsize-LikeH4">Max Mustermann</p>
<p>Musterstraße 123<br>12345 Musterstadt</p>
<p>Telefon: <a href="tel:+491234567890"><strong>0123-456789-0</strong></a><br>E-Mail: <a href="mailto:max@mustermann.de">max@mustermann.de</a></p>',
				'link' => null,
				'column_width' => '2/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 2,
				'identifier' => 'dummy_row_overflow',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p class="Textsize-LikeH4">Unsere &Ouml;ffnungszeiten</p>
<table> <tbody> <tr> <td>Montag &ndash; Freitag</td> <td><strong>08:00</strong> bis <strong>18:00 Uhr</strong></td> </tr> <tr> <td>Samstag &ndash; Sonntag</td> <td><strong>09:00</strong> bis <strong>14:00 Uhr</strong></td> </tr> </tbody> </table>
',
				'link' => null,
				'column_width' => '3/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 3,
				'identifier' => 'dummy_row_overflow',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p class="Textsize-LikeH4">Max Mustermann</p>
<p>Musterstraße 123<br>12345 Musterstadt</p>
<p>Telefon: <a href="tel:+491234567890"><strong>0123-456789-0</strong></a><br>E-Mail: <a href="mailto:max@mustermann.de">max@mustermann.de</a></p>',
				'link' => null,
				'column_width' => '3/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 5,
				'identifier' => 'dummy_row_overflow',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
<h5>Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</h5>
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
<p>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>',
				'link' => null,
				'column_width' => '3/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 6,
				'identifier' => 'dummy_nested',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 7,
				'identifier' => 'dummy_nested',
				'widget_template_id' => 1,
				'parent_id' => 4,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Child of inactive</p>',
				'link' => null,
				'column_width' => '2/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 8,
				'identifier' => 'dummy_multi_row',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 2</p>',
				'link' => null,
				'column_width' => '3/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 9,
				'identifier' => 'dummy_multi_row',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 1 - first (half indented) and last</p>',
				'link' => null,
				'column_width' => '1/2',
				'column_indent' => '1/2',
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => '{"ak":"av","ck":"cv"}',
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 10,
				'identifier' => 'dummy_multi_row',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 3 with module</p><module class="mceNonEditable" data-identifier="breadcrumbs" data-label="Breadcrumbs">{"includeHomepage":true,"includeCurrentPage":true,"showOnHomepage":false,"homepageId":""}</module><p>And Text after Module</p>',
				'link' => null,
				'column_width' => '2/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 3,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 11,
				'identifier' => 'dummy_multi_row',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 4 (last in row)</p>',
				'link' => null,
				'column_width' => '1/4',
				'column_indent' => null,
				'column_last' => 1,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 4,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 12,
				'identifier' => 'dummy_multi_row',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 5 (RTL)</p>',
				'link' => null,
				'column_width' => '1/4',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 1,
				'css_class' => 'AdditionalClass',
				'data' => null,
				'form_id' => null,
				'system_order' => 5,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 13,
				'identifier' => 'dummy_single_row',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 2</p>',
				'link' => null,
				'column_width' => '1/2',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 2,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 14,
				'identifier' => 'dummy_single_row',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Element 1</p>',
				'link' => null,
				'column_width' => '1/2',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 15,
				'identifier' => 'dummy_nested',
				'widget_template_id' => 1,
				'parent_id' => 7,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Child of child of inactive</p>',
				'link' => null,
				'column_width' => '2/3',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 16,
				'identifier' => 'dummy_narrow',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Narrow</p>',
				'link' => null,
				'column_width' => '1/1',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 17,
				'identifier' => 'dummy_narrow',
				'widget_template_id' => 1,
				'parent_id' => 16,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Narrow</p>',
				'link' => null,
				'column_width' => '1/2',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 18,
				'identifier' => 'inline_img',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Widget with inline img tag</p><p><awyiss-responsive-image>{"mediaId":"4"}</awyiss-responsive-image></p><p>between two paragraphs</p>',
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 19,
				'identifier' => 'custom_template',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Widget with custom template</p>',
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => 2,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 20,
				'identifier' => 'custom_template',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Widget with custom template that sets a content row class</p>',
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 21,
				'identifier' => 'custom_template',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p>Widget with regular template</p>',
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 22,
				'identifier' => 'double_inline_img',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '<p><awyiss-responsive-image>{"mediaId":"4"}</awyiss-responsive-image></p><p>Widget with two inline img</p><p><awyiss-responsive-image>{"mediaId":"2"}</awyiss-responsive-image></p>',
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'system_order' => 1,
				'active' => 1,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
			[
				'id' => 23,
				'identifier' => 'with_survey',
				'widget_template_id' => 1,
				'parent_id' => null,
				'title' => null,
				'subtitle' => null,
				'text' => '',
				'link' => null,
				'column_width' => '4/5',
				'column_indent' => null,
				'column_last' => 0,
				'column_rtl' => 0,
				'css_class' => null,
				'data' => null,
				'form_id' => null,
				'survey_id' => 3,
				'system_order' => 1,
				'active' => 0,
				'deleted' => 0,
				'created_by' => 1,
				'created_on' => (new \Cake\I18n\DateTime('now'))->format('Y-m-d H:i:s'),
				'changed_by' => null,
				'changed_on' => null,
				'deleted_by' => null,
				'deleted_on' => null,
			],
		];

		$lo_table = $this->table('widgets');
		$lo_table->insert($la_data)->save();
	}
}
