<?php declare(strict_types=1);


namespace Awyiss\Controller;


use Awyiss\Authentication\IdentityAwareTrait;
use Awyiss\Awyiss;
use Awyiss\Core\LocalConfig;
use Awyiss\Event\EventListenersProvider;
use Awyiss\Middleware\LocaleMiddleware;
use Awyiss\Model\Table;
use Awyiss\Routing\Router;
use Awyiss\View\BackendView;
use Cake\Core\Configure;
use Cake\Database\Expression\QueryExpression;
use Cake\Datasource\FactoryLocator;
use Cake\Datasource\Paging\PaginatedInterface;
use Cake\Datasource\QueryInterface;
use Cake\Datasource\RepositoryInterface;
use Cake\Event\EventInterface;
use Cake\Http\Exception\RedirectException;
use Cake\Http\Response;
use Cake\ORM\Query\SelectQuery;
use Cake\Utility\Hash;
use Cake\Utility\Inflector;
use Psr\Http\Message\UriInterface;


/**
 * @property \Authentication\Controller\Component\AuthenticationComponent $Authentication
 * @property \Awyiss\Controller\Component\AuthorizationComponent $Authorization
 * @property \Awyiss\Controller\Component\CategoriesComponent $Categories
 * @property \Awyiss\Controller\Component\PaginateComponent $Paginate
 * @property \Awyiss\Controller\Component\SystemOrderComponent $SystemOrder
 */
abstract class BackendController extends AppController {
	use IdentityAwareTrait;


	/**
	 * @see AuthorizationComponent
	 * @var array Settings for the AuthorizationComponent
	 */
	protected array $authorization = [];
	/**
	 * @see CategoriesComponent
	 * @var array Settings for the CategoriesComponent
	 */
	protected array $categories = [];
	/**
	 * @var array<string>  A list of properties that will be merged with values from the database configuration
	 */
	protected array $customConfigProperties = [
		'categories',
		'eventTrigger',
		'paginate',
		'publicationData',
		'systemOrder',
	];
	/**
	 * @see \Awyiss\Controller\Component\EventTriggerComponent
	 * @var array Settings for the EventTriggerComponent
	 */
	protected array $eventTrigger = [];
	/**
	 * @see initializeOverviewWhere()
	 * @var array Settings used in initializeOverviewWhere()
	 */
	protected array $overviewWhere;
	/**
	 * @inheritDoc
	 * @var array
	 */
	protected array $paginate = [
		'enabled' => false,
	];
	/**
	 * @var array Settings for the PublicationDataBehavior
	 */
	protected array $publicationData = [];
	/**
	 * @see SystemOrderComponent
	 * @var array Settings for the SystemOrderComponent
	 */
	protected array $systemOrder = [];


	/**
	 * @throws \Exception
	 */
	public function initialize(): void {
		parent::initialize();

		//Load event listeners for the current controller in the "backend"-folder
		EventListenersProvider::loadListener($this->getName(), Awyiss::REALM_BACKEND);

		//Merge the config properties with custom configuration from the database
		$ls_scope = $this->getName();

		foreach ($this->customConfigProperties as $ls_property) {
			$ls_path = implode('.', ['Awyiss', $ls_scope, Awyiss::REALM_BACKEND, $ls_property]);
			$la_customConfig = Configure::read($ls_path);
			if ($la_customConfig && is_array($this->$ls_property)) {
				$this->$ls_property = Hash::merge($this->$ls_property, $la_customConfig);
			}
		}

		$lo_request = Router::getRequest();
		if ($lo_request) {
			$ls_path = $lo_request->getUri()->getPath();

			$ls_lang = LocaleMiddleware::getLanguage()->shortcode;

			$la_parts = [
				'lang' => $lo_request->getParam('lang'),
				'controller' => $lo_request->getParam('controller'),
				'action' => $lo_request->getParam('action'),
				'_name' => Awyiss::REALM_BACKEND,
			];
			$la_parts += $lo_request->getParam('parts');

			if ($lo_request->getParam('prefix') !== 'Backend') {
				$la_prefixParts = explode('/', $lo_request->getParam('prefix'));
				array_shift($la_prefixParts);

				$ls_prefixName = implode('_', $la_prefixParts);
				$ls_prefixName .= '_' . $lo_request->getParam('controller');
				$ls_prefixName = strtolower($ls_prefixName);

				$la_parts['_name'] = Awyiss::REALM_BACKEND . '::' . $ls_prefixName;
			}

			//Redirect if the url does not match the one generated by Router::url(), for example when the controller action is omitted.
			$ls_testPath = Router::url($la_parts);
			if (!str_starts_with($ls_path, $ls_testPath)) {
				$this->redirect(
					Router::url(
						[
							'_name' => $la_parts['_name'],
							'?' => $lo_request->getParam('?'),
						] + $lo_request->getParam('parts') + ['lang' => $ls_lang]
					),
					301
				);
			}

			//Redirect to the same route if the last character is not a slash
			if (!$lo_request->getParam('fullSlug') && !str_ends_with($ls_path, '/') && !$lo_request->getParam('parts')) {
				$this->redirect($ls_path . '/', 301);
			}

			$this->loadComponent('Authentication.Authentication');

			$this->loadComponent('Authorization', $this->authorization);

			$this->loadComponent('EventTrigger', $this->eventTrigger);

			$this->loadComponent('Flash', ['key' => Inflector::underscore($this->getName())]);

			if ($this->defaultTable) {
				$this->loadComponent('Categories', $this->categories);

				$this->loadComponent('SystemOrder', $this->systemOrder);
			}

			$this->loadComponent('Paginate', $this->paginate);
		}

		//Detect the available commands
		if (!Configure::read('AvailableCommands')) {
			/** @var \Queue\Model\Table\QueuedJobsTable $lo_queue */
			$lo_queue = FactoryLocator::get('Table')->get('Queue.QueuedJobs');
			$lo_queue->createJob('Queue.Execute', [
				'command' => 'bin/cake media detect_available_commands',
				'log' => true,
			], [
				'group' => 'general',
				'priority' => 1,
				'reference' => 'system::detect_available_commands',
			]);
		}

		//Sets the name of the viewClass to be used by the viewBuilder
		$this->viewBuilder()->setClassName(BackendView::class);
	}


	/**
	 * @inheritDoc
	 * @param \Cake\Datasource\RepositoryInterface|\Cake\Datasource\QueryInterface|string|null $object
	 * @param array $settings
	 * @return \Cake\Datasource\Paging\PaginatedInterface
	 */
	public function paginate(
		RepositoryInterface|QueryInterface|string|null $object = null,
		array $settings = []
	): PaginatedInterface {
		return $this->Paginate->paginate($object, $settings);
	}


	/**
	 * Returns the query used in the overview-method of most controllers.
	 *
	 * @return \Cake\ORM\Query\SelectQuery|null
	 */
	abstract public function getOverviewQuery(): ?SelectQuery;


	/**
	 * Returns the set where-clauses used in the overview-method of most controllers.
	 *
	 * When $key is empty, the whole array is returned.
	 *
	 * When $key is set, the corresponding value is returned if set, otherwise null.
	 *
	 * @param string|null $key
	 * @param null $default
	 * @return mixed
	 */
	public function getOverviewWhere(?string $key = null, null $default = null): mixed {
		if (!isset($this->overviewWhere)) {
			$this->overviewWhere = [];
			$this->initializeOverviewWhere();
		}

		if ($key) {
			return $this->overviewWhere[ Inflector::underscore($key) ] ?? $default;
		}

		return $this->overviewWhere;
	}


	/**
	 * Sets the where-clauses used in the overview-method of most controllers.
	 *
	 * @param array|string $key
	 * @param mixed $value
	 * @return BackendController
	 * @noinspection PhpUnused
	 */
	public function setOverviewWhere(string|array $key, mixed $value = null): static {
		if (is_string($key)) {
			$this->overviewWhere[ $key ] = $value;
		}
		else {
			$this->overviewWhere = $key;
		}

		return $this;
	}


	/**
	 * Sets the initial where-clauses used in the overview-method of most controllers.
	 * This allows dynamic values to be set, depending on the state of the app.
	 *
	 * @return void
	 */
	protected function initializeOverviewWhere(): void {
	}


	/**
	 * Saves the order of the systemOrder field in the database for a given list of items.
	 *
	 * @return void
	 * @throws \Exception
	 */
	public function saveSystemOrder(): void {
		$this->Authorization->ensure('read');

		$lo_request = Router::getRequest();

		$ls_tableName = $this->SystemOrder->getConfig('tableName');
		$lo_table = $this->{$ls_tableName};

		if (!$lo_table->hasBehavior('SystemOrder') || !$lo_table->getBehavior('SystemOrder')->getConfig('enabled')) {
			if ($this->request->accepts('application/json')) {
				$this->viewBuilder()->setOption('serialize', ['success', 'message']);

				$this->set('success', false);
				$this->set('message', __d('system', 'system_order_not_enabled'));

				// Set the view class to JSON
				$this->viewBuilder()->setClassName('Json');

				// Setting the response status to 422 Unprocessable Entity
				$this->response = $this->response->withStatus(422, 'Unable to process entity');
			}
			else {
				$this->Flash->error(__d('system', 'system_order_not_enabled'));
				throw new RedirectException(Router::url(['action' => 'overview'], true), 302);
			}
		}

		$ls_field = Inflector::variable($this->SystemOrder->getConfig('field', 'systemOrder'));
		if ($ls_field !== 'systemOrder') {
			if ($this->request->accepts('application/json')) {
				$this->viewBuilder()->setOption('serialize', ['success', 'message']);

				$this->set('success', false);
				$this->set('message', __d('system', 'system_order_manual_order_is_disabled'));

				// Set the view class to JSON
				$this->viewBuilder()->setClassName('Json');

				// Setting the response status to 422 Unprocessable Entity
				$this->response = $this->response->withStatus(422, 'Unable to process entity');
			}
			else {
				$this->Flash->error(__d('system', 'system_order_manual_order_is_disabled'));
				throw new RedirectException(Router::url(['action' => 'overview'], true), 302);
			}
		}

		/** @noinspection DuplicatedCode */
		$li_affectedRows = $this->_saveSystemOrder($lo_request->getData('order'), $lo_table);

		if ($this->request->accepts('application/json')) {
			$this->viewBuilder()->setOption('serialize', ['success', 'message']);

			$this->set('success', $li_affectedRows !== false);
			$this->set('message', $li_affectedRows > 0 ? __d('system', 'system_order_saved') : __d('system', 'system_order_not_saved'));

			// Set the view class to JSON
			$this->viewBuilder()->setClassName('Json');

			if ($li_affectedRows === false) {
				// Setting the response status to 422 Unprocessable Entity
				$this->response = $this->response->withStatus(422, 'Unable to process entity');
			}
		}
		else {
			if ($li_affectedRows) {
				$this->Flash->success(__d('system', 'system_order_saved'));
			}
			else {
				$this->Flash->error(__d('system', 'system_order_not_saved'));
			}

			throw new RedirectException(Router::url(['action' => 'overview'], true), 302);
		}
	}


	/**
	 * Sets user configuration based on the provided url parameters and redirects to the previous page.
	 */
	public function userConfiguration(): void {
		$lo_request = Router::getRequest();

		$ls_scope = Inflector::underscore($this->getName());

		if ($ls_scope === 'dashboard') {
			$ls_scope = 'system';
		}

		$ls_scope = Inflector::singularize($ls_scope);
		$ls_scope = Inflector::pluralize($ls_scope);
		$ls_scope = Inflector::underscore($ls_scope);

		$ls_identifier = $lo_request->getParam('identifier') ?: $lo_request->getData('identifier');
		$lx_value = $lo_request->getParam('value') ?: $lo_request->getData('value');

		/** @var \Awyiss\Model\Entity\User $lo_identity */
		$lo_identity = $this->getIdentity();

		$la_config = [
			'user_id' => $lo_identity->id,
			'scope' => $ls_scope,
			'identifier' => $ls_identifier,
		];

		//Get the UserConfiguration table and fetch a matching config
		/** @var \Awyiss\Model\Table $lo_table */
		$lo_table = $this->fetchTable('UserConfiguration');
		$lo_config = $lo_table->find()->where([
			'user_id' => $lo_identity->id,
			'scope' => $ls_scope,
			'identifier' => $ls_identifier,
		])->first();

		if (!$lo_config) {
			$lo_config = $lo_table->newDefaultEntity();
			$la_config['value'] = $lx_value;
			$lo_config = $lo_table->patchEntity($lo_config, $la_config);
		}
		else {
			$lo_config->set('value', $lx_value);
		}

		// TODO: Delete the entity if the value is the default value of the config option

		$lb_success = $lo_table->save($lo_config);
		if ($lb_success) {
			$lo_identity->resetConfiguration();
		}

		if ($this->request->is('ajax')) {
			$this->viewBuilder()->setOption('serialize', ['success', 'message']);
			$this->set('success', !!$lb_success);
			$this->set('message', $lb_success ? __d('system', 'user_configuration_saved') : __d('system', 'user_configuration_not_saved'));

			// Set the view class to JSON
			$this->viewBuilder()->setClassName('Json');

			if (!$lb_success) {
				// Setting the response status to 422 Unprocessable Entity
				$this->response = $this->response->withStatus(422, 'Unable to process entity');
			}
		}
		else {
			$ls_referer = $lo_request->referer();
			if ($ls_identifier === 'paginate.limit') {
				// Remove "page:X" from the referer url
				$ls_referer = preg_replace('/\/page:\d+/', '', $ls_referer);

				//Remove double slashes
				$ls_referer = preg_replace('/([^:])\/\//', '$1/', $ls_referer);
			}

			throw new RedirectException($ls_referer, 302);
		}
	}


	/**
	 * beforeRender callback.
	 *
	 * @param EventInterface<\Cake\Controller\Controller> $event Event.
	 * @return void
	 */
	public function beforeRender(EventInterface $event): void {
		$this->set('config', Configure::read());
		$this->set('localConfig', LocalConfig::read());

		// Disable the layout for ajax requests
		if (
			$this->request->is('ajax') &&
			($this->request->getData('reload_form') || $this->request->getParam('ajaxForm'))
		) {
			$lo_viewBuilder = $this->viewBuilder();
			$lo_viewBuilder->disableAutoLayout();

			// Consume the flash messages to prevent them from being displayed the next time the page is loaded
			$ls_controller = Inflector::underscore($this->getName());
			$this->request->getFlash()->consume($ls_controller);
		}
	}


	/**
	 * @param \Cake\Event\EventInterface $event
	 * @param \Psr\Http\Message\UriInterface|array|string $url
	 * @param \Cake\Http\Response $response
	 * @return void
	 */
	public function beforeRedirect(EventInterface $event, UriInterface|array|string $url, Response $response): void {
		if ($this->request->is('ajax')) {
			// Consume the flash messages to prevent them from being displayed the next time the page is loaded
			$ls_controller = Inflector::underscore($this->getName());
			$this->request->getFlash()->consume($ls_controller);
		}
	}


	/**
	 * @param array $requestData
	 * @param \Awyiss\Model\Table $table
	 * @return int
	 */
	protected function _saveSystemOrder(array $requestData, Table $table): int {
		/*
		 * Build an array of the order data
		 * In the first level, the key is the parent id, the value is an array of the child ids
		 * In the second level, the value is the child id, the key is the order, offset by -1
		 */
		$la_orderData = [];
		foreach ($requestData as $li_parentId => $la_children) {
			foreach ($la_children as $li_order => $li_id) {
				$la_orderData[] = [
					'id' => $li_id,
					'parentId' => $li_parentId === 0 ? null : $li_parentId,
					'systemOrder' => $li_order + 1,
				];
			}
		}

		$lo_schema = $table->getSchema();

		/** @noinspection PhpUnnecessaryLocalVariableInspection */
		$li_affectedRows = $table->updateAll(function (QueryExpression $expression) use ($la_orderData, $lo_schema) {
			$lo_parentCase = $expression->case();
			$lo_systemOrderCase = $expression->case();

			foreach ($la_orderData as $la_data) {
				$lo_parentCase->when(['id' => $la_data['id']])->then($la_data['parentId'], 'integer');
				$lo_systemOrderCase->when(['id' => $la_data['id']])->then($la_data['systemOrder'], 'integer');
			}

			if ($lo_schema->hasColumn('parent_id')) {
				return [
					'parent_id' => $lo_parentCase,
					'system_order' => $lo_systemOrderCase,
				];
			}


			return [
				'system_order' => $lo_systemOrderCase,
			];
		}, [
			'id IN' => array_column($la_orderData, 'id'),
		]);


		return $li_affectedRows;
	}
}
