<?php declare(strict_types=1);


namespace Awyiss\Controller;


use Awyiss\Awyiss;
use Awyiss\Event\EventListenersProvider;
use Awyiss\Middleware\LocaleMiddleware;
use Awyiss\Routing\Router;
use Awyiss\View\BackendView;
use Cake\Core\Configure;
use Cake\Datasource\Paging\PaginatedInterface;
use Cake\Datasource\QueryInterface;
use Cake\Datasource\RepositoryInterface;
use Cake\Utility\Hash;
use Cake\Utility\Inflector;


/**
 * @property \Authentication\Controller\Component\AuthenticationComponent $Authentication
 * @property \Awyiss\Controller\Component\AuthorizationComponent $Authorization
 * @property \Awyiss\Controller\Component\CategoriesComponent $Categories
 * @property \Awyiss\Controller\Component\SystemOrderComponent $SystemOrder
 */
abstract class BackendController extends AppController {
	/**
	 * @see AuthorizationComponent
	 * @var array Settings for the AuthorizationComponent
	 */
	protected array $authorization = [];
	/**
	 * @see CategoriesComponent
	 * @var array Settings for the CategoriesComponent
	 */
	protected array $categories = [];
	/**
	 * @var array<string>  A list of properties that will be merged with values from the database configuration
	 */
	protected array $customConfigProperties = [
		'categories',
		'eventTrigger',
		'paginate',
		'systemOrder',
	];
	/**
	 * @see \Awyiss\Controller\Component\EventTriggerComponent
	 * @var array Settings for the EventTriggerComponent
	 */
	protected array $eventTrigger = [];
	/**
	 * @see initializeOverviewWhere()
	 * @var array Settings used in initializeOverviewWhere()
	 */
	protected array $overviewWhere;
	/**
	 * @inheritDoc
	 * @var array
	 */
	protected array $paginate = [];
	/**
	 * @see SystemOrderComponent
	 * @var array Settings for the SystemOrderComponent
	 */
	protected array $systemOrder = [];


	/**
	 * @throws \Exception
	 */
	public function initialize(): void {
		parent::initialize();

		//Load event listeners for the current controller in the "backend"-folder
		EventListenersProvider::loadListener($this->getName(), Awyiss::REALM_BACKEND);

		//Merge the config properties with custom configuration from the database
		$ls_scope = $this->getName();

		foreach ($this->customConfigProperties as $ls_property) {
			$ls_path = implode('.', ['Awyiss', $ls_scope, Awyiss::REALM_BACKEND, $ls_property]);
			$la_customConfig = Configure::read($ls_path);
			if ($la_customConfig && is_array($this->$ls_property)) {
				$this->$ls_property = Hash::merge($this->$ls_property, $la_customConfig);
			}
		}

		$lo_request = Router::getRequest();
		if ($lo_request) {
			$ls_path = $lo_request->getUri()->getPath();

			$ls_lang = LocaleMiddleware::getLanguage()->shortcode;

			//Redirect if the url does not match the one generated by Router::url(), for example when the controller action is omitted.
			$ls_testPath = Router::url(['_name' => Awyiss::REALM_BACKEND] + $lo_request->getParam('parts') + ['lang' => $ls_lang]);
			if (!str_starts_with($ls_path, $ls_testPath)) {
				$this->redirect(
					Router::url(
						[
							'_name' => Awyiss::REALM_BACKEND,
							'?' => $lo_request->getParam('?'),
						] + $lo_request->getParam('parts') + ['lang' => $ls_lang]
					),
					301
				);
			}

			//Redirect to the same route if the last character is not a slash
			if (!$lo_request->getParam('fullSlug') && !str_ends_with($ls_path, '/') && !$lo_request->getParam('parts')) {
				$this->redirect($ls_path . '/', 301);
			}

			$this->loadComponent('Authentication.Authentication');

			$this->loadComponent('Authorization', $this->authorization);

			$this->loadComponent('EventTrigger', $this->eventTrigger);

			$this->loadComponent('Flash', ['key' => Inflector::underscore($this->getName())]);

			if ($this->defaultTable) {
				$this->loadComponent('Categories', $this->categories);

				$this->loadComponent('SystemOrder', $this->systemOrder);
			}
		}

		//Sets the name of the viewClass to be used by the viewBuilder
		$this->viewBuilder()->setClassName(BackendView::class);
	}


	/**
	 * @inheritDoc
	 * @param \Cake\Datasource\RepositoryInterface|\Cake\Datasource\QueryInterface|string|null $object
	 * @param array $settings
	 * @return \Cake\Datasource\Paging\PaginatedInterface
	 * @noinspection PhpParameterNameChangedDuringInheritanceInspection
	 */
	public function paginate(
		RepositoryInterface|QueryInterface|string|null $ao_object = null,
		array $aa_settings = []
	): PaginatedInterface {
		$la_settings = $aa_settings;
		$la_settings += [
			'order' => [
				'title' => 'asc',
			],
		];


		return parent::paginate($ao_object, $la_settings);
	}


	/**
	 * Returns the set where-clauses used in the overview-method of most controllers.
	 *
	 * When $ax_key is empty, the whole array is returned.
	 *
	 * When $ax_key is set, the corresponding value is returned if set, otherwise null.
	 *
	 * @param string|null $ax_key
	 * @param null $ax_default
	 * @return mixed
	 */
	public function getOverviewWhere(?string $ax_key = null, null $ax_default = null): mixed {
		if (!isset($this->overviewWhere)) {
			$this->overviewWhere = [];
			$this->initializeOverviewWhere();
		}

		if ($ax_key) {
			return $this->overviewWhere[ Inflector::underscore($ax_key) ] ?? $ax_default;
		}


		return $this->overviewWhere;
	}


	/**
	 * Sets the where-clauses used in the overview-method of most controllers.
	 *
	 * @param array|string $ax_key
	 * @param mixed $ax_value
	 * @return BackendController
	 * @noinspection PhpUnused
	 */
	public function setOverviewWhere(string|array $ax_key, mixed $ax_value = null): static {
		if (is_string($ax_key)) {
			$this->overviewWhere[ $ax_key ] = $ax_value;
		}
		else {
			$this->overviewWhere = $ax_key;
		}


		return $this;
	}


	/**
	 * Sets the initial where-clauses used in the overview-method of most controllers.
	 * This allows dynamic values to be set, depending on the state of the app.
	 *
	 * @return void
	 */
	protected function initializeOverviewWhere(): void {
	}
}
