<?php declare(strict_types=1);


namespace Awyiss\Controller\Component;


use Cake\Controller\Component;
use Cake\Event\Event;
use Cake\Event\EventInterface;
use Cake\Utility\Inflector;


//use Cake\Http\Response;

/**
 * This component dispatches all possible controller events with a modified name.
 * This allows listening to, for example, `Controller.Foobar.beforeSave` instead of just `Controller.beforeSave`,
 * with "Foobar" being the name of the currently used controller
 */
class EventTriggerComponent extends Component {
	/**
	 * @inheritDoc
	 *
	 * @var array<string, mixed>
	 */
	protected array $_defaultConfig = [
		'enabled' => TRUE,
	];


	/**
	 * When calling this method, the whole componend will be enabled.
	 *
	 * @return void
	 */
	public function enable(): void {
		$this->setConfig('enabled', TRUE);
	}


	/**
	 * When calling this method, the whole componend will be disabled.
	 *
	 * @return void
	 */
	public function disable(): void {
		$this->setConfig('enabled', FALSE);
	}


	/**
	 * Is called when the component is initialized
	 *
	 * @param array<string, mixed> $aa_config The configuration settings provided to this component.
	 *
	 * @noinspection PhpParameterNameChangedDuringInheritanceInspection
	 */
	public function initialize(array $aa_config): void {
		$this->dispatchEvent('initialize', NULL, $aa_config);
	}


	/**
	 * Is called before the controller’s beforeFilter method, but after the controller’s initialize() method.
	 *
	 * @noinspection PhpUnused
	 */
	public function beforeFilter(EventInterface $ao_event): void {
		$this->dispatchEvent('beforeFilter', $ao_event);
	}


	/**
	 * Is called after the controller’s beforeFilter method but before the controller executes the current action handler.
	 */
	public function startup(EventInterface $ao_event): void {
		$this->dispatchEvent('startup', $ao_event);
	}


	/**
	 * Is called after the controller executes the requested action’s logic, but before the controller renders views and layout.
	 */
	public function beforeRender(EventInterface $ao_event): void {
		$this->dispatchEvent('beforeRender', $ao_event);
	}


	/**
	 * Is called before output is sent to the browser.
	 *
	 * @noinspection PhpUnused
	 */
	public function afterFilter(EventInterface $ao_event): void {
		$this->dispatchEvent('afterFilter', $ao_event);
	}


	/**
	 * Actually dispatch the event, generated by the listener methods in this component
	 *
	 * @param string $as_name
	 * @param NULL|EventInterface $ao_event
	 * @param ...$aa_arguments
	 *
	 * @return void
	 */
	protected function dispatchEvent(string $as_name, ?EventInterface $ao_event, ...$aa_arguments): void {
		if (!$this->getConfig('enabled')) {
			return;
		}

		$lo_controller = $this->getController();
		$ls_controllerName = Inflector::singularize($lo_controller->getName());

		$lo_event = new Event('Controller.' . $ls_controllerName . '.' . $as_name, $lo_controller, ($ao_event?->getData() ?? []) + $aa_arguments);
		$lo_controller->getEventManager()->dispatch($lo_event);

		if ($lo_event->isStopped()) {
			$ao_event->stopPropagation();
			$ao_event->setResult($lo_event->getResult());
		}
	}
}
