<?php declare(strict_types=1);


namespace Awyiss\Controller\Component;


use Cake\Controller\Component;
use Cake\Event\Event;
use Cake\Event\EventInterface;


//use Cake\Http\Response;

/**
 * This component dispatches all possible controller events with a modified name.
 * This allows listening to, for example, `Controller.Foobar.beforeSave` instead of just `Controller.beforeSave`,
 * with "Foobar" being the name of the currently used controller
 *
 * @method \Awyiss\Controller\AppController getController()
 * @noinspection PhpFullyQualifiedNameUsageInspection
 */
class EventTriggerComponent extends Component {
	/**
	 * @inheritDoc
	 */
	protected array $_defaultConfig = [ // phpcs:ignore
		'enabled' => true,
	];


	/**
	 * When calling this method, the whole component will be enabled.
	 *
	 * @return void
	 */
	public function enable(): void {
		$this->setConfig('enabled', true);
	}


	/**
	 * When calling this method, the whole component will be disabled.
	 *
	 * @return void
	 */
	public function disable(): void {
		$this->setConfig('enabled', false);
	}


	/**
	 * Is called when the component is initialized
	 *
	 * @param array<string, mixed> $config The configuration settings provided to this component.
	 */
	public function initialize(array $config): void {
		$this->dispatchEvent('initialize', null, $config);
	}


	/**
	 * Is called before the controller’s beforeFilter method, but after the controller’s initialize() method.
	 *
	 * @param \Cake\Event\EventInterface $event
	 */
	public function beforeFilter(EventInterface $event): void {
		$this->dispatchEvent('beforeFilter', $event);
	}


	/**
	 * Is called after the controller’s beforeFilter method but before the controller executes the current action handler.
	 *
	 * @param \Cake\Event\EventInterface $event
	 */
	public function startup(EventInterface $event): void {
		$this->dispatchEvent('startup', $event);
	}


	/**
	 * Is called after the controller executes the requested action’s logic, but before the controller renders views and layout.
	 *
	 * @param \Cake\Event\EventInterface $event
	 */
	public function beforeRender(EventInterface $event): void {
		$this->dispatchEvent('beforeRender', $event);
	}


	/**
	 * Is called before output is sent to the browser.
	 *
	 * @param \Cake\Event\EventInterface $event
	 * @noinspection PhpUnused
	 */
	public function afterFilter(EventInterface $event): void {
		$this->dispatchEvent('afterFilter', $event);
	}


	/**
	 * Actually dispatch the event, generated by the listener methods in this component
	 *
	 * @param string $name
	 * @param EventInterface|null $event
	 * @param mixed ...$arguments
	 * @return void
	 */
	protected function dispatchEvent(string $name, ?EventInterface $event, mixed ...$arguments): void {
		if (!$this->getConfig('enabled')) {
			return;
		}

		$controller = $this->getController();

		$newEvent = new Event('Controller.' . $controller->getName() . '.' . $name, $controller, ($event?->getData() ?? []) + $arguments);
		$controller->getEventManager()->dispatch($newEvent);

		if ($newEvent->isStopped()) {
			$event->stopPropagation();
			$event->setResult($newEvent->getResult());
		}
	}
}
